### ISSUE TITLE
 RELEASE.2021-04-18T19-26-29Z - CRC check failed

### ISSUE THREAD

**Issue by ToLToL** [minio/minio#12110]
#### Context

Federation (etcd + coredns), 3 clusters (1 with 2 pools)
Logger and audit enabled
Scrape Prometheus metrics through `/minio/prometheus/metrics`.
Upgrade `RELEASE.2021-04-06T23-11-00Z` to the latest `RELEASE.2021-04-18T19-26-29Z`

I get:

```
API: SYSTEM()
Time: 09:02:44 UTC 04/21/2021
DeploymentID: a4d7c650-dcf6-4134-9f60-455ee6f8cf2c
Error: CRC check failed (msgp.errWrapped)
       4: cmd/logger/logonce.go:53:logger.(*logOnceType).logOnceIf()
       3: cmd/logger/logonce.go:93:logger.LogOnceIf()
       2: cmd/data-usage-cache.go:546:cmd.(*dataUsageCache).load()
       1: cmd/erasure.go:461:cmd.erasureObjects.nsScanner.func3()

API: SYSTEM()
Time: 08:23:34 UTC 04/21/2021
DeploymentID: ca742616-fed7-4ddd-b842-48f25833c35a
Error: unexpected literal count, want 17 bytes, but only 14 is available (msgp.errWrapped)
       4: cmd/logger/logonce.go:53:logger.(*logOnceType).logOnceIf()
       3: cmd/logger/logonce.go:93:logger.LogOnceIf()
       2: cmd/data-usage-cache.go:546:cmd.(*dataUsageCache).load()
       1: cmd/erasure.go:461:cmd.erasureObjects.nsScanner.func3()

API: SYSTEM()
Time: 08:23:40 UTC 04/21/2021
DeploymentID: ca742616-fed7-4ddd-b842-48f25833c35a
Error: sequence stream 0, repeat requested, but no history (msgp.errWrapped)
       4: cmd/logger/logonce.go:53:logger.(*logOnceType).logOnceIf()
       3: cmd/logger/logonce.go:93:logger.LogOnceIf()
       2: cmd/data-usage-cache.go:546:cmd.(*dataUsageCache).load()
       1: cmd/erasure.go:461:cmd.erasureObjects.nsScanner.func3()

API: SYSTEM()
Time: 08:23:43 UTC 04/21/2021
DeploymentID: ca742616-fed7-4ddd-b842-48f25833c35a
Error: rle symbol 117 >= max 36 (msgp.errWrapped)
       4: cmd/logger/logonce.go:53:logger.(*logOnceType).logOnceIf()
       3: cmd/logger/logonce.go:93:logger.LogOnceIf()
       2: cmd/data-usage-cache.go:546:cmd.(*dataUsageCache).load()
       1: cmd/erasure.go:461:cmd.erasureObjects.nsScanner.func3()

API: SYSTEM()
Time: 08:23:45 UTC 04/21/2021
DeploymentID: ca742616-fed7-4ddd-b842-48f25833c35a
Error: tableLog too large (msgp.errWrapped)
       4: cmd/logger/logonce.go:53:logger.(*logOnceType).logOnceIf()
       3: cmd/logger/logonce.go:93:logger.LogOnceIf()
       2: cmd/data-usage-cache.go:546:cmd.(*dataUsageCache).load()
       1: cmd/erasure.go:461:cmd.erasureObjects.nsScanner.func3()

API: SYSTEM()
Time: 08:23:58 UTC 04/21/2021
DeploymentID: ca742616-fed7-4ddd-b842-48f25833c35a
Error: unexpected literal count, want 17 bytes, but only 0 is available (msgp.errWrapped)
       4: cmd/logger/logonce.go:53:logger.(*logOnceType).logOnceIf()
       3: cmd/logger/logonce.go:93:logger.LogOnceIf()
       2: cmd/data-usage-cache.go:546:cmd.(*dataUsageCache).load()
       1: cmd/erasure.go:461:cmd.erasureObjects.nsScanner.func3()

API: SYSTEM()
Time: 08:28:57 UTC 04/21/2021
DeploymentID: ca742616-fed7-4ddd-b842-48f25833c35a
Error: unexpected EOF (msgp.errWrapped)
       4: cmd/logger/logonce.go:53:logger.(*logOnceType).logOnceIf()
       3: cmd/logger/logonce.go:93:logger.LogOnceIf()
       2: cmd/data-usage-cache.go:546:cmd.(*dataUsageCache).load()
       1: cmd/erasure.go:461:cmd.erasureObjects.nsScanner.func3()
```

#### Problem

I don't get all prometheus metrics.

**Comment by klauspost** [comment]
Logs aren't related to prometheus, but looks like some sort of data corruption with the scanner data. This shouldn't really happen.

I would treat the updated server carefully.

**Comment by ToLToL** [comment]
I have these logs as well:

**Comment by ToLToL** [comment]
I also have these kinds of logs:

```
API: SYSTEM()
Time: 07:58:20 UTC 04/21/2021
DeploymentID: ca742616-fed7-4ddd-b842-48f25833c35a
Error: Disk: /mnt/data2  -> .minio.sys/buckets/{BUCKET}/.usage-cache.bin/8b351454-4926-417e-89f9-7cd481806dc0/part.1 - content hash does not match - expected ec2d0f76a4811665b835aaf7f346101ee61e28a8600321c6fe9958aa2b0740ea, got 9939f5c67a0f290367a040445471f8132acc45ca1f0e0216c5b7975db574c214 (*errors.errorString)
       2: cmd/bitrot-streaming.go:162:cmd.(*streamingBitrotReader).ReadAt()
       1: cmd/erasure-decode.go:164:cmd.(*parallelReader).Read.func1()
```

**Comment by klauspost** [comment]
Is it possible for you to collect all files from this `{BUCKET}/.usage-cache.bin/` from all disks and zip them up? That would help a lot with debugging.

**Comment by klauspost** [comment]
(they may have been overwritten in the meantime though)

**Comment by ToLToL** [comment]
Indeed, they have been overwritten. Do you want them anyway?

**Comment by harshavardhana** [comment]
This should be addressed by #12111

**Comment by harshavardhana** [comment]
And also #12116

**Comment by ToLToL** [comment]
@harshavardhana @klauspost 

Thanks, it's fixed for clusters with 1 pool in `2021-04-22T15:44:28Z`, but still have the same error for a cluster with 2 pools:

```
API: SYSTEM()
Time: 07:54:59 UTC 04/26/2021
DeploymentID: a4d7c650-dcf6-4134-9f60-455ee6f8cf2c
Error: CRC check failed (msgp.errWrapped)
       4: cmd/logger/logonce.go:53:logger.(*logOnceType).logOnceIf()
       3: cmd/logger/logonce.go:93:logger.LogOnceIf()
       2: cmd/data-usage-cache.go:546:cmd.(*dataUsageCache).load()
       1: cmd/erasure.go:461:cmd.erasureObjects.nsScanner.func3()

API: SYSTEM()
Time: 08:08:47 UTC 04/26/2021
DeploymentID: a4d7c650-dcf6-4134-9f60-455ee6f8cf2c
Error: unexpected literal count, want 62 bytes, but only 7 is available (msgp.errWrapped)
       4: cmd/logger/logonce.go:53:logger.(*logOnceType).logOnceIf()
       3: cmd/logger/logonce.go:93:logger.LogOnceIf()
       2: cmd/data-usage-cache.go:546:cmd.(*dataUsageCache).load()
       1: cmd/erasure.go:461:cmd.erasureObjects.nsScanner.func3()

API: SYSTEM()
Time: 08:10:38 UTC 04/26/2021
DeploymentID: a4d7c650-dcf6-4134-9f60-455ee6f8cf2c
Error: match offset (515) bigger than current history (76) (msgp.errWrapped)
       4: cmd/logger/logonce.go:53:logger.(*logOnceType).logOnceIf()
       3: cmd/logger/logonce.go:93:logger.LogOnceIf()
       2: cmd/data-usage-cache.go:546:cmd.(*dataUsageCache).load()
       1: cmd/erasure.go:461:cmd.erasureObjects.nsScanner.func3()

API: SYSTEM()
Time: 08:12:10 UTC 04/26/2021
DeploymentID: a4d7c650-dcf6-4134-9f60-455ee6f8cf2c
Error: match offset (1247885) bigger than current history (0) (msgp.errWrapped)
       4: cmd/logger/logonce.go:53:logger.(*logOnceType).logOnceIf()
       3: cmd/logger/logonce.go:93:logger.LogOnceIf()
       2: cmd/data-usage-cache.go:546:cmd.(*dataUsageCache).load()
       1: cmd/erasure.go:461:cmd.erasureObjects.nsScanner.func3()
```

I don't know whether it's related or not but I have inconsistent prometheus metrics from this cluster:

e.g.: `sum by (job) (disk_storage_total)`
![Screenshot 2021-04-26 at 11 18 06](https://user-images.githubusercontent.com/39993930/116059396-151ac500-a681-11eb-9c9d-0dba33b34a84.png)
