### ISSUE TITLE
Minio Server responds with "You need to enable JavaScript to run this app."

### ISSUE THREAD

**Issue by sunsdy2018** [minio/minio#12654]
My OS is Windows 10.

The version of minio.exe is:
![image](https://user-images.githubusercontent.com/38706610/125032045-fba1ea80-e0bf-11eb-8dd4-5f5ee92783a4.png)

Download the minio.exe with the above version from the offical website and save it to e:/software/. Open a cmd console and redirect to e:/software/ and execute the following command:
![image](https://user-images.githubusercontent.com/38706610/125035029-e333cf00-e0c3-11eb-85fc-8221c4d6a625.png)

It tells minio.exe runs normally. Open Google Chrome and open http://127.0.0.1:9080/ as follows:
![image](https://user-images.githubusercontent.com/38706610/125035190-14140400-e0c4-11eb-905a-0e2e84ad8c85.png)

The response headers are:
![image](https://user-images.githubusercontent.com/38706610/125035252-2726d400-e0c4-11eb-8b3b-4231e56e3bab.png)

The console of chrome shows two errors as follows:
![image](https://user-images.githubusercontent.com/38706610/125035315-3e65c180-e0c4-11eb-97de-02ca522afde9.png)

**Comment by sunsdy2018** [comment]
The JavaScript is enabled as follows:
![image](https://user-images.githubusercontent.com/38706610/125038641-3ad43980-e0c8-11eb-9abb-4741d0121090.png)

**Comment by harshavardhana** [comment]
This a mime-type issue was reported here https://github.com/minio/console/issues/802#issuecomment-872460857 

The solution is 

There is a reported issue with golang & windows, on which MIME types can be changed by some applications and return non-valid MIME types: https://github.com/golang/go/issues/32350. This issue is exclusive for Windows OS and doesn't apply for Linux / Apple users

As a temporal fix, you may want to try to insert the following keys in windows registry:

```
[HKEY_CLASSES_ROOT\.js]
"Content Type"="text/javascript"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.js]
"Content Type"="text/javascript"
```

**Comment by nathanieloon** [comment]
@harshavardhana I've got the same issue on macOS, so it seems to be more widespread than windows?

![image](https://user-images.githubusercontent.com/5898957/126582175-302725df-9122-436b-93b8-87bbf72d4368.png)

**Comment by ctorrisi** [comment]
@harshavardhana I am having the same issue on macOS.

**Comment by harshavardhana** [comment]
> @harshavardhana I am having the same issue on macOS.

There is an issue with UI asset generation - making a new release now.

This was fixed in b865b9f4 - original issue is different.

**Comment by midium81** [comment]
Even with latest version and proposed registry changes I'm still not able to access the console
![image](https://user-images.githubusercontent.com/39514370/129194079-b0a314c1-9476-4818-8f37-84b3d71ce523.png)

Used version:
![image](https://user-images.githubusercontent.com/39514370/129194119-6baa9674-3fd4-406a-a180-cfa1f03940e3.png)

**Comment by rush2sk8** [comment]
I am having the same problem as @midium81. Version 
![image](https://user-images.githubusercontent.com/6383959/129230649-c071f4a0-5009-4668-9a7a-6936ee6f0a4b.png)

**Comment by siniankxq** [comment]
I am having the same problem as @midium81. Version
![image](https://user-images.githubusercontent.com/48594394/129294237-aef50ba9-57e8-4d77-913a-c92c81624d0b.png)

**Comment by trlthiago** [comment]
Hi, it seems the problem still happening

![image](https://user-images.githubusercontent.com/6925748/131274271-48cc70be-c38c-4b61-9e95-05fda5b8df82.png)

But, changing de registry as mentioned before, it got working 🙂 :

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.js]
"Content Type"="text/javascript"
```
