### ISSUE TITLE
dashboard TOTAL OBJECTS According to not complete

### ISSUE THREAD

**Issue by dreamwolftears** [minio/minio#13802]
![d](https://user-images.githubusercontent.com/12526208/144347706-21d0b69b-d5b9-434e-97b5-18860567010c.png)

**Comment by harshavardhana** [comment]
@dreamwolftears this is fixed in console in latest releases - please upgrade.

**Comment by dreamwolftears** [comment]
@harshavardhana  my minio version RELEASE.2021-11-24T23-19-33Z，TOTAL OBJECTS Still showing incomplete。

**Comment by harshavardhana** [comment]
> @harshavardhana  my minio version RELEASE.2021-11-24T23-19-33Z，TOTAL OBJECTS Still showing incomplete。

It won't be updated right away, scanner cycles update the values in due time.

It's not instant after objects are uploaded.
