### ISSUE TITLE
Unable to read from ... unexpected EOF

### ISSUE THREAD

**Issue by haslersn** [minio/minio#14868]
When I run the following command against my MinIO server (version `2022-05-04T07:45:27Z`)

```
mc cat --json kube/cluster01-postgres-backups/spilo/stuvus-synapse-db/b4b1e236-f8c3-468b-bb5a-55469e499adb/wal/12/wal_005/0000003B000000E3000000B6.lzma
```

then it only dumps part of the file and then stops with the following error:

```json
{
 "status": "error",
 "error": {
  "message": "Unable to read from `kube/cluster01-postgres-backups/spilo/stuvus-synapse-db/b4b1e236-f8c3-468b-bb5a-55469e499adb/wal/12/wal_005/0000003B000000E3000000B6.lzma`.",
  "cause": {
   "message": "unexpected EOF",
   "error": {}
  },
  "type": "fatal",
  "sysinfo": {
   "host.arch": "amd64",
   "host.cpus": "8",
   "host.lang": "go1.17.9",
   "host.name": "beaver",
   "host.os": "linux",
   "mem.heap.total": "12 MB",
   "mem.heap.used": "3.7 MB",
   "mem.total": "22 MB",
   "mem.used": "3.7 MB"
  }
 }
}
```

I also downloaded it without `--json`, because the JSON gets written to stdout instead of stderr. When trying to uncompress it, I have another indication that indeed only part of the file was downloaded:

```
$ unlzma downloaded.lzma >/dev/null
unlzma: downloaded.lzma: Unexpected end of input
```

<details>
<summary>Server log</summary>

```
minio-ss-1-0 minio 
minio-ss-1-0 minio API: GetObject(bucket=cluster01-postgres-backups, object=spilo/stuvus-synapse-db/b4b1e236-f8c3-468b-bb5a-55469e499adb/wal/12/wal_005/0000003B000000E3000000B6.lzma, versionId=6b4f9e4e-d9d2-4831-af43-3bd15e4172d6)
minio-ss-1-0 minio Time: 11:24:17 UTC 05/05/2022
minio-ss-1-0 minio DeploymentID: 73a34713-7b8c-4d45-98ba-6e9c6a8cc1df
minio-ss-1-0 minio RequestID: 16EC31BE7FCB9364
minio-ss-1-0 minio RemoteHost: 10.53.214.246
minio-ss-1-0 minio Host: minio-ss-1-0.minio-old.s3.svc.cluster.local:9000
minio-ss-1-0 minio UserAgent: MinIO (linux; amd64) minio-go/v7.0.24 mc/RELEASE.2022-04-26T18-00-22Z
minio-ss-1-0 minio Error: Unable to write all the data to client sio: authentication failed (*fmt.wrapError)
minio-ss-1-0 minio        5: cmd/object-handlers.go:542:cmd.objectAPIHandlers.getObjectHandler()
minio-ss-1-0 minio        4: cmd/object-handlers.go:599:cmd.objectAPIHandlers.GetObjectHandler()
minio-ss-1-0 minio        3: cmd/http-tracer.go:171:cmd.Trace()
minio-ss-1-0 minio        2: cmd/handler-utils.go:375:cmd.httpTraceHdrs.func1()
minio-ss-1-0 minio        1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```

</details>

<details>
<summary>Trace</summary>

```
2022-05-05T13:24:17:000 [200 OK] s3.HeadObject minio-ss-0-0.minio-old.s3.svc.cluster.local:9000/cluster01-postgres-backups/spilo/stuvus-synapse-db/b4b1e236-f8c3-468b-bb5a-55469e499adb/wal/12/wal_005/0000003B000000E3000000B6.lzma 10.53.214.246     163.578ms    ↑ 196 B ↓ 502 B
2022-05-05T13:24:17:000 [200 OK] s3.GetObject minio-ss-1-0.minio-old.s3.svc.cluster.local:9000/cluster01-postgres-backups/spilo/stuvus-synapse-db/b4b1e236-f8c3-468b-bb5a-55469e499adb/wal/12/wal_005/0000003B000000E3000000B6.lzma?versionId=6b4f9e4e-d9d2-4831-af43-3bd15e4172d6  10.53.214.246     77.636ms     ↑ 196 B ↓ 128 KiB
```

</details>

<details>
<summary>Server info</summary>

```
$ mc admin info kube
●  minio-ss-0-0.minio-old.s3.svc.cluster.local:9000
   Uptime: 10 hours 
   Version: 2022-05-04T07:45:27Z
   Network: 6/6 OK 
   Drives: 4/4 OK 
   Pool: 1st

●  minio-ss-0-1.minio-old.s3.svc.cluster.local:9000
   Uptime: 10 hours 
   Version: 2022-05-04T07:45:27Z
   Network: 6/6 OK 
   Drives: 4/4 OK 
   Pool: 1st

●  minio-ss-0-2.minio-old.s3.svc.cluster.local:9000
   Uptime: 10 hours 
   Version: 2022-05-04T07:45:27Z
   Network: 6/6 OK 
   Drives: 4/4 OK 
   Pool: 1st

●  minio-ss-1-0.minio-old.s3.svc.cluster.local:9000
   Uptime: 2 minutes 
   Version: 2022-05-04T07:45:27Z
   Network: 6/6 OK 
   Drives: 4/4 OK 
   Pool: 2nd

●  minio-ss-1-1.minio-old.s3.svc.cluster.local:9000
   Uptime: 2 minutes 
   Version: 2022-05-04T07:45:27Z
   Network: 6/6 OK 
   Drives: 4/4 OK 
   Pool: 2nd

●  minio-ss-1-2.minio-old.s3.svc.cluster.local:9000
   Uptime: 3 minutes 
   Version: 2022-05-04T07:45:27Z
   Network: 6/6 OK 
   Drives: 4/4 OK 
   Pool: 2nd

9.0 TiB Used, 23 Buckets, 1,999,954 Objects, 291,062 Versions
24 drives online, 0 drives offline
```

</details>

**Comment by harshavardhana** [comment]
Looks like you have Kes setup with encryption?
```
-ss-1-0 minio Error: Unable to write all the data to client sio: authentication failed (*fmt.wrapError)
minio-ss-1-0 minio        5: cmd/object-handlers.go:542:cmd.objectAPIHandlers.getObjectHandler()
minio-ss-1-0 minio        4: cmd/object-handlers.go:599:cmd.objectAPIHandlers.GetObjectHandler()
```

And it's not reachable? Please provide your server setup details with all environment variables that are set.

**Comment by harshavardhana** [comment]
You are also running different MinIO versions in same deployment, please avoid that

```
minio-ss-1-0.minio-old.s3.svc.cluster.local:9000
   Uptime: 10 hours 
   Version: 2022-04-30T22:23:53Z
   Network: 6/6 OK 
   Drives: 4/4 OK 
   Pool: 2nd

●  minio-ss-1-1.minio-old.s3.svc.cluster.local:9000
   Uptime: 10 hours 
   Version: 2022-04-30T22:23:53Z
   Network: 6/6 OK 
   Drives: 4/4 OK 
   Pool: 2nd

●  minio-ss-1-2.minio-old.s3.svc.cluster.local:9000
   Uptime: 10 hours 
   Version: 2022-04-30T22:23:53Z
   Network: 6/6 OK 
   Drives: 4/4 OK 
   Pool: 2nd
```

Do not know how you are doing that..

**Comment by haslersn** [comment]
> You are also running different MinIO versions in same deployment

Interesting. It seems the update 10 hours ago wasn't rolled out to one of the two StatefulSets. I fixed that (and edited the server info in the original post), but unfortunately the issue persists.


> you have Kes setup with encryption?

Yes

> And it's not reachable?

It is reachable. Other encrypted objects can be read just fine. And the first 131072 Bytes of the object in question can be read. After 131072 Bytes it outputs the stated error.

> Please provide your server setup details with all environment variables that are set.

<details>
<summary>Example environment on minio-ss-0-0</summary>

```ini
PATH=/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=minio-ss-0-0
container=oci
MINIO_ACCESS_KEY_FILE=access_key
MINIO_SECRET_KEY_FILE=secret_key
MINIO_ROOT_USER_FILE=access_key
MINIO_ROOT_PASSWORD_FILE=secret_key
MINIO_KMS_SECRET_KEY_FILE=kms_master_key
MINIO_UPDATE_MINISIGN_PUBKEY=redacted
MINIO_CONFIG_ENV_FILE=config.env
MINIO_KMS_KES_KEY_FILE=/etc/minio/private.key
MINIO_KMS_KES_CERT_FILE=/etc/minio/public.crt
MINIO_KMS_KES_KEY_NAME=my-minio-key
MINIO_BROWSER_REDIRECT_URL=https://console.redacted
MINIO_SERVER_URL=https://redacted
MINIO_STORAGE_CLASS_STANDARD=EC:5
MINIO_ROOT_USER=redacted
MINIO_KMS_KES_ENDPOINT=https://kes.s3.svc.cluster.local:7373
MINIO_PROMETHEUS_AUTH_TYPE=public
MINIO_PROMETHEUS_JOB_ID=minio
MINIO_ROOT_PASSWORD=redacted
MINIO_CONSOLE_ADDRESS=:9443
MINIO_PROMETHEUS_URL=http://prometheus-k8s.prometheus.svc.cluster.local:9090
MINIO_ZONE0_PORT_9000_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
MINIO_OLD_PORT_9000_TCP=tcp://10.96.22.93:9000
MINIO_ZONE0_SERVICE_PORT_HTTPS_MINIO=9000
MINIO_ZONE0_PORT_9443_TCP_ADDR=10.96.6.179
KUBERNETES_PORT=tcp://10.96.0.1:443
MINIO_OLD_PORT_9000_TCP_PROTO=tcp
MINIO_OLD_PORT_9000_TCP_ADDR=10.96.22.93
MINIO_OLD_PORT_9443_TCP=tcp://10.96.22.93:9443
MINIO_ZONE0_PORT_9443_TCP=tcp://10.96.6.179:9443
MINIO_ZONE0_PORT_9443_TCP_PROTO=tcp
MINIO_ZONE0_PORT_9443_TCP_PORT=9443
KUBERNETES_SERVICE_PORT=443
MINIO_OLD_PORT=tcp://10.96.22.93:9000
MINIO_OLD_PORT_9443_TCP_PROTO=tcp
MINIO_ZONE0_SERVICE_HOST=10.96.6.179
MINIO_ZONE0_PORT_9000_TCP_ADDR=10.96.6.179
KUBERNETES_SERVICE_HOST=10.96.0.1
MINIO_OLD_SERVICE_PORT=9000
MINIO_OLD_SERVICE_PORT_HTTPS_MINIO=9000
MINIO_OLD_PORT_9000_TCP_PORT=9000
MINIO_OLD_PORT_9443_TCP_PORT=9443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
MINIO_ZONE0_SERVICE_PORT=9000
MINIO_ZONE0_PORT_9000_TCP=tcp://10.96.6.179:9000
MINIO_ZONE0_PORT_9000_TCP_PORT=9000
MINIO_OLD_SERVICE_HOST=10.96.22.93
MINIO_OLD_SERVICE_PORT_HTTPS_CONSOLE=9443
MINIO_OLD_PORT_9443_TCP_ADDR=10.96.22.93
MINIO_ZONE0_SERVICE_PORT_HTTPS_CONSOLE=9443
MINIO_ZONE0_PORT=tcp://10.96.6.179:9000
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP_PORT=443
TERM=xterm
HOME=/
```

</details>

<details>
<summary>Kubernetes manifests for the MinIO containers</summary>

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-ss-0
spec:
  replicas: 3
  serviceName: minio-old
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      component: minio-old
  template:
    metadata:
      labels:
        component: minio-old
    spec:
      priorityClassName: system-cluster-critical
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/memory-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/network-unavailable
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/pid-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/unschedulable
          operator: Exists
          effect: NoSchedule
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      containers:
        - name: minio
          image: quay.io/minio/minio:RELEASE.2022-05-04T07-45-27Z
          args:
            - server
            - https://minio-ss-0-{0...2}.minio-old.s3.svc.cluster.local/disk{0...3}
            - https://minio-ss-1-{0...2}.minio-old.s3.svc.cluster.local/disk{0...3}
            - --certs-dir
            - /etc/minio
            - --config-dir
            - /etc/minio
          env:
            - name: MINIO_STORAGE_CLASS_STANDARD
              value: EC:5
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  key: accesskey
                  name: root-credentials-old
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: secretkey
                  name: root-credentials-old
            - name: MINIO_KMS_KES_ENDPOINT
              value: https://kes.s3.svc.cluster.local:7373
            - name: MINIO_KMS_KES_KEY_FILE
              value: /etc/minio/private.key
            - name: MINIO_KMS_KES_CERT_FILE
              value: /etc/minio/public.crt
            - name: MINIO_KMS_KES_KEY_NAME
              value: my-minio-key
            - name: MINIO_CONSOLE_ADDRESS
              value: :9443
            - name: MINIO_BROWSER_REDIRECT_URL
              value: https://console.redacted
            - name: MINIO_SERVER_URL
              value: https://redacted
            - name: MINIO_PROMETHEUS_AUTH_TYPE
              value: public
            - name: MINIO_PROMETHEUS_URL
              value: http://prometheus-k8s.prometheus.svc.cluster.local:9090
            - name: MINIO_PROMETHEUS_JOB_ID
              value: minio
          resources:
            limits:
              memory: 8Gi
            requests:
              memory: 8Gi
          volumeMounts:
            - name: "0"
              mountPath: /disk0
            - name: "1"
              mountPath: /disk1
            - name: "2"
              mountPath: /disk2
            - name: "3"
              mountPath: /disk3
            - name: cert
              mountPath: /etc/minio/CAs/public.crt
              subPath: ca.crt
            - name: cert
              mountPath: /etc/minio/private.key
              subPath: tls.key
            - name: cert
              mountPath: /etc/minio/public.crt
              subPath: tls.crt
      volumes:
        - name: cert
          secret:
            secretName: minio-old-cert
  volumeClaimTemplates:
    - metadata:
        name: "0"
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: s3-zone-0
        resources:
          requests:
            storage: 1863Gi
    - metadata:
        name: "1"
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: s3-zone-0
        resources:
          requests:
            storage: 1863Gi
    - metadata:
        name: "2"
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: s3-zone-0
        resources:
          requests:
            storage: 1863Gi
    - metadata:
        name: "3"
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: s3-zone-0
        resources:
          requests:
            storage: 1863Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-ss-1
spec:
  replicas: 3
  serviceName: minio-old
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      component: minio-old
  template:
    metadata:
      labels:
        component: minio-old
    spec:
      priorityClassName: system-cluster-critical
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/memory-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/network-unavailable
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/pid-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/unschedulable
          operator: Exists
          effect: NoSchedule
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      containers:
        - name: minio
          image: quay.io/minio/minio:RELEASE.2022-05-04T07-45-27Z
          args:
            - server
            - https://minio-ss-0-{0...2}.minio-old.s3.svc.cluster.local/disk{0...3}
            - https://minio-ss-1-{0...2}.minio-old.s3.svc.cluster.local/disk{0...3}
            - --certs-dir
            - /etc/minio
            - --config-dir
            - /etc/minio
          env:
            - name: MINIO_STORAGE_CLASS_STANDARD
              value: EC:5
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  key: accesskey
                  name: root-credentials-old
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: secretkey
                  name: root-credentials-old
            - name: MINIO_KMS_KES_ENDPOINT
              value: https://kes.s3.svc.cluster.local:7373
            - name: MINIO_KMS_KES_KEY_FILE
              value: /etc/minio/private.key
            - name: MINIO_KMS_KES_CERT_FILE
              value: /etc/minio/public.crt
            - name: MINIO_KMS_KES_KEY_NAME
              value: my-minio-key
            - name: MINIO_CONSOLE_ADDRESS
              value: :9443
            - name: MINIO_BROWSER_REDIRECT_URL
              value: https://console.redacted
            - name: MINIO_SERVER_URL
              value: https://redacted
            - name: MINIO_PROMETHEUS_AUTH_TYPE
              value: public
            - name: MINIO_PROMETHEUS_URL
              value: http://prometheus-k8s.prometheus.svc.cluster.local:9090
            - name: MINIO_PROMETHEUS_JOB_ID
              value: minio
          resources:
            limits:
              memory: 8Gi
            requests:
              memory: 8Gi
          volumeMounts:
            - name: "0"
              mountPath: /disk0
            - name: "1"
              mountPath: /disk1
            - name: "2"
              mountPath: /disk2
            - name: "3"
              mountPath: /disk3
            - name: cert
              mountPath: /etc/minio/CAs/public.crt
              subPath: ca.crt
            - name: cert
              mountPath: /etc/minio/private.key
              subPath: tls.key
            - name: cert
              mountPath: /etc/minio/public.crt
              subPath: tls.crt
      volumes:
        - name: cert
          secret:
            secretName: minio-old-cert
  volumeClaimTemplates:
    - metadata:
        name: "0"
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: s3-zone-1
        resources:
          requests:
            storage: 14902Gi
    - metadata:
        name: "1"
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: s3-zone-1
        resources:
          requests:
            storage: 14902Gi
    - metadata:
        name: "2"
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: s3-zone-1
        resources:
          requests:
            storage: 14902Gi
    - metadata:
        name: "3"
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: s3-zone-1
        resources:
          requests:
            storage: 14902Gi
```

</details>

<details>
<summary>Kubernetes manifests for KES containers</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kes
spec:
  replicas: 3
  selector:
    matchLabels:
      component: kes
  template:
    metadata:
      labels:
        component: kes
    spec:
      priorityClassName: system-cluster-critical
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/memory-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/network-unavailable
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/pid-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/unschedulable
          operator: Exists
          effect: NoSchedule
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
      containers:
        - name: kes
          securityContext:
            readOnlyRootFilesystem: true
          image: quay.io/minio/kes:v0.19.2
          command:
            - sh
            - -c
            - |
              export MINIO_OLD_IDENTITY="$(/kes identity of /etc/kes/minio-old.crt)"
              exec /kes server --config=/etc/kes/server-config.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/kes/server-config.yaml
              subPath: server-config.yaml
            # Public key of MinIO (for mTLS between MinIO and KES).
            # This is only used to compute the `$MINIO_IDENTITY` prior to startup.
            - name: minio-old-cert
              mountPath: /etc/kes/minio-old.crt
              subPath: tls.crt
            # We trust the CA that signs MinIO's certificate.
            # This file is honored, because `/etc/ssl/certs` is one of the directories where Go
            # reads CA certificates.
            - name: kes-cert
              mountPath: /etc/ssl/certs/s3-ca.crt
              subPath: ca.crt
            # Private key of KES (for mTLS between MinIO and KES).
            - name: kes-cert
              mountPath: /etc/kes/tls.key
              subPath: tls.key
            # Public key of KES (for mTLS between MinIO and KES).
            - name: kes-cert
              mountPath: /etc/kes/tls.crt
              subPath: tls.crt
      volumes:
        - name: config
          secret:
            secretName: kes-config
        - name: kes-cert
          secret:
            secretName: kes-cert
        - name: minio-old-cert
          secret:
            secretName: minio-old-cert
```

</details>

<details>
<summary>KES server config</summary>

```yaml
address: 0.0.0.0:7373
root: _ # Effectively disabled since no root identity necessary.
tls:
  key: /etc/kes/tls.key # Path to the TLS private key
  cert: /etc/kes/tls.crt # Path to the TLS certificate
  proxy:
    identities: []
    header:
      cert: X-Tls-Client-Cert
policy:
  my-policy:
    paths:
      - /v1/key/create/*
      - /v1/key/generate/*
      - /v1/key/decrypt/*
    identities:
      - ${MINIO_OLD_IDENTITY}
cache:
  expiry:
    any: 5m0s
    unused: 20s
log:
  error: on
  audit: off
keys:
  vault:
    endpoint: http://kms-vault-active.kms.svc:8200
    #namespace: "" # An optional Vault namespace. See: https://www.vaultproject.io/docs/enterprise/namespaces/index.html
    prefix: s3 # An optional K/V prefix. The server will store keys under this prefix.
    approle: # AppRole credentials. See: https://www.vaultproject.io/docs/auth/approle.html
      id: redacted
      secret: redacted
      retry: 15s # Duration until the server tries to re-authenticate after connection loss.
    status: # Vault status configuration. The server will periodically reach out to Vault to check its status.
      ping: 10s # Duration until the server checks Vault's status again.
```

</details>

**Comment by klauspost** [comment]
[this](https://github.com/minio/sio/blob/83dd737d26dbcf4847f48ecec77c2c13f739eb25/dare.go#L268) is the only place where this error can occur.

It seems rather broad, but considering the first 2 packages can be decoded, the key is correct. Maybe @aead can shed some light on which conditions this can occur under.

**Comment by haslersn** [comment]
From the code it reads like the authentication of the AEAD fails. This might be data corruption. Is the object split into shards (data and parity) first and then authenticatedly encrypted, or first authenticatedly encrypted and then split into shards?

**Comment by harshavardhana** [comment]
Did you replace your drives on the second pool in the past ?

**Comment by haslersn** [comment]
> Did you replace your drives on the second pool in the past ?

No

**Comment by harshavardhana** [comment]
> > Did you replace your drives on the second pool in the past ?
> 
> No

When was this object originally created ?

**Comment by harshavardhana** [comment]
Please also attach `mc support inspect alias/path/to/object/**`

**Comment by haslersn** [comment]
> When was this object originally created ?

On 16 Feb 2022:

```
[2022-02-16 19:40:47 CET] 4.8MiB STANDARD 6b4f9e4e-d9d2-4831-af43-3bd15e4172d6 v1 PUT 0000003B000000E3000000B6.lzma
```

> Please also attach `mc support inspect alias/path/to/object/**`

[inspect.b915f39d.zip](https://github.com/minio/minio/files/8649108/inspect.b915f39d.zip)

**Comment by harshavardhana** [comment]
So this is also a versioned bucket ?

**Comment by haslersn** [comment]
Yes. It used to be versioned. Versioning on that bucket is suspended since April. The version I posted is the only version of that object (that shows up with `mc ls --versions`.

**Comment by harshavardhana** [comment]
This issue is mostly fixed with 

```
commit d480022711f508cdbe1c06e44ce1a33d7a07998e
Author: Harshavardhana <harsha@minio.io>
Date:   Mon May 30 12:43:54 2022 -0700

    fix: invalidate outdated disks appropriately during readAllXL (#15002)
    
    readAllXL would return inlined data for outdated disks
    causing "read" to return incorrect content to the client,
    
    this PR fixes this behavior by making sure we skip such
    outdated disks appropriately based on the latest ModTime
    on the disk.
```

**Comment by haslersn** [comment]
I updated to version `2022-06-03T01:40:53Z` and still get the same error.

**Comment by harshavardhana** [comment]
> I updated to version `2022-06-03T01:40:53Z` and still get the same error.

Then this data is not recoverable, it may be something happened in the past that has trickled down.

There was an erasure coding padding issue in the past. Since you have an encrypted setup I can't see the decoding part locally.

So this data is gone at best.
