### ISSUE TITLE
"volume not found" error on MultipartUpload, but PutObject works

### ISSUE THREAD

**Issue by mshanmu** [minio/minio#15740]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Has 3 server pools, on one of the server pool, with 4 nodes having 1 disk each, 2 nodes were replaced.

Healing is in progress, unfortunately, it is very slow. 

In this scenario, trying a PutObject works fine, but using MultipartUpload fails with 404 "volume not found", see below,

API: NewMultipartUpload(bucket=abc, object=xyz)
Time: <snip>
DeploymentID: <snip>
RequestID: <snip>
RemoteHost: <snip>
Host: <snip>
UserAgent: MinIO 
Error: volume not found (cmd.StorageErr)
       objectErasureMap=&{{{0 0} {{map[] true}} map[xyz] 0}}
        5: cmd/erasure-multipart.go:209:cmd.erasureObjects.ListMultipartUploads()
        4: cmd/erasure-sets.go:1090:cmd.(*erasureSets).ListMultipartUploads()
        3: cmd/erasure-server-pool.go:1274:cmd.(*erasureServerPools).NewMultipartUpload()
        2: cmd/object-handlers.go:2323:cmd.objectAPIHandlers.NewMultipartUploadHandler()
        1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()

Questions,

1. Why the inconsistent behavior with regard to PutObject and MultipartUpload operations?
2. How to speed up the healing process, even if it means the cluster is frozen for write operations?

## Expected Behavior

MultipartUpload works.

## Current Behavior

MultipartUpload fails.

## Possible Solution

Worked around this issue, by disabling multi part uploads from python client.

## Steps to Reproduce (for bugs)

1. Setup a 4 node/1disk cluster
2. Create bucket xyz
3. Copy lots of files to xyz bucket
4. Replace 2 nodes 
5. Try mc cp <10 MiB file> alias/xyz, notice it fails with Bucket xyz does not exist
6. Try mc cp --disable-multipart <10 MB file> alias/xyz, notice it succeeds

## Your Environment

* Version used (`minio --version`): RELEASE.2022-04-16T04-26-02Z
* Server setup and configuration: kubernetes v1.21.3
* Operating System and version (`uname -a`): Linux

**Comment by harshavardhana** [comment]
> API: NewMultipartUpload(bucket=abc, object=xyz)
> Time:
> DeploymentID:
> RequestID:
> RemoteHost:
> Host:
> UserAgent: MinIO
> Error: volume not found (cmd.StorageErr)
> objectErasureMap=&{{{0 0} {{map[] true}} map[xyz] 0}}
> 5: cmd/erasure-multipart.go:209:cmd.erasureObjects.ListMultipartUploads()
> 4: cmd/erasure-sets.go:1090:cmd.(*erasureSets).ListMultipartUploads()
> 3: cmd/erasure-server-pool.go:1274:cmd.(*erasureServerPools).NewMultipartUpload()
> 2: cmd/object-handlers.go:2323:cmd.objectAPIHandlers.NewMultipartUploadHandler()
> 1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()

This is because of quorum requirements for "each" pool @mshanmu multipart-uploads are required to be saved at a separate location on the disks. 

You have lost the write quorum on the disks on one of your pools, NOTE: Pools are not a way to increase your SLA by any means you are still bound by the write quorum of each pool. 

Luckily since PUT() is getting scheduled because it relies on GET which succeeds even if 2 (drives are down) . We can certainly relax the requirement for ListMultipartUploads() call to be "read" specific so that it proceeds without throwing up an error. 

However, your deployment is poor @mshanmu you are going to face issues if you deploy in this fashion and keep expanding perpetually.  You have architected this setup without our help. As I have suggested in the past you must get a subscription with us for production support we can help you in these types of situations (even to avoid them in the first place)

**Comment by harshavardhana** [comment]
Ah actually this is already fixed in later releases. 

Your release has this code.

```go
                        if err == errDiskNotFound {
                                continue
                        }
                        if err == errFileNotFound {
                                return result, nil
                        }
                        logger.LogIf(ctx, err)
                        return result, toObjectErr(err, bucket, object)
                }
                break
        }
```

newer releases have this - so this is fixed since

```go
                if err != nil {
                        if errors.Is(err, errDiskNotFound) {
                                continue
                        }
                        if errors.Is(err, errFileNotFound) || errors.Is(err, errVolumeNotFound) {
                                return result, nil
                        }
                        logger.LogIf(ctx, err)
                        return result, toObjectErr(err, bucket, object)
                }
                break
        }
```


```
git tag --contains 236ef03dbd
RELEASE.2022-07-15T03-44-22Z
RELEASE.2022-07-17T15-43-14Z
RELEASE.2022-07-24T01-54-52Z
RELEASE.2022-07-24T17-09-31Z
RELEASE.2022-07-26T00-53-03Z
RELEASE.2022-07-29T19-40-48Z
RELEASE.2022-07-30T05-21-40Z
RELEASE.2022-08-02T23-59-16Z
RELEASE.2022-08-05T23-27-09Z
RELEASE.2022-08-08T18-34-09Z
RELEASE.2022-08-11T04-37-28Z
RELEASE.2022-08-13T21-54-44Z
RELEASE.2022-08-22T23-53-06Z
RELEASE.2022-08-25T07-17-05Z
RELEASE.2022-08-26T19-53-15Z
RELEASE.2022-09-01T23-53-36Z
RELEASE.2022-09-07T22-25-02Z
RELEASE.2022-09-17T00-09-45Z
```

**Comment by mshanmu** [comment]
Makes sense, Thanks, @harshavardhana !!

**Comment by mshanmu** [comment]
@harshavardhana , I am looking at the master branch, that check seems to be still present, see below,

https://github.com/minio/minio/blob/master/cmd/erasure-multipart.go#L262

```
if errors.Is(err, errFileNotFound) || errors.Is(err, errVolumeNotFound) {
    return result, nil
}
```

**Comment by harshavardhana** [comment]
> if errors.Is(err, errFileNotFound) || errors.Is(err, errVolumeNotFound) {
>     return result, nil
> }

The check is needed to ensure we can ignore @mshanmu :-) you are reading it wrong.

**Comment by mshanmu** [comment]
Ah, getting old :) Thanks, @harshavardhana

**Comment by mshanmu** [comment]
Just a FYI for people hitting this issue in future, took the following steps,

1. Increased the healing speed using "mc admin config set <alias> heal " command, by tweaking max_sleep and max_io parameters.
2. Waited for couple of hours for healing to complete.
3. Even after healing was complete, multipart uploads were still failing.
4. Recreated the multipart directory under  /export/data/.minio.sys/ path
5. Multipart uploads started working.

In hindsight, I should have tried recreating the multipart directory before even healing completed. That might have probably fixed the issue.
