### ISSUE TITLE
Objects in the bucket not deleted after a certain service lifetime, until service restarts

### ISSUE THREAD

**Issue by vdombrovski** [minio/minio#19140]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

This is a direct followup to #19015, which doesn't seem to completely fix the issue. Basically, after some time, deleting objects returns a success call without actually deleting them.

I'm running the 2024-02-17T01-15-57Z release which includes the fix mentioned in https://github.com/minio/minio/pull/19017

After service restart, the deletion works as expected. This has been consistently reproduced in at least 3 distributed setups running this release.

## Expected Behavior

After a rm is issued, the object is deleted.

## Current Behavior

The object is never deleted, this until the service is restarted.

```
mc ls local/share/testfile
[2024-02-26 09:08:40 UTC]     5B STANDARD testfile
mc rm local/share/testfile
Removed `local/share/testfile`.
mc ls local/share/testfile
[2024-02-26 09:08:40 UTC]     5B STANDARD testfile
```

## Possible Solution

Something that might help: on the broken instance, debug logs show os.Rename operations, however no os.Remove are performed. Example for one node (g2n12):
```
2024-02-26T11:47:59.111 [OS] os.Rename g2n12:9000 /mnt/disk15/local/share/testfile/0d463649-d97a-4ed3-a329-fc1bc0e28fac -> /mnt/disk15/local/.minio.sys/tmp/.trash/ba6f5984-61fe-418c-8bad-fc067cdfe829 10.656µs
2024-02-26T11:47:59.111 [OS] os.Rename g2n12:9000 /mnt/disk15/local/share/testfile/0d463649-d97a-4ed3-a329-fc1bc0e28fac -> /mnt/disk15/local/.minio.sys/tmp/.trash/ba6f5984-61fe-418c-8bad-fc067cdfe829 4.051µs
2024-02-26T11:47:59.111 [OS] os.Rename g2n12:9000 /mnt/disk15/local/share/testfile/xl.meta -> /mnt/disk15/local/.minio.sys/tmp/.trash/7031e4d0-d369-4a4d-afc4-f77eace1d257 3.596µs
2024-02-26T11:47:59.111 [OS] os.Rename g2n12:9000 /mnt/disk15/local/share/testfile/xl.meta -> /mnt/disk15/local/.minio.sys/tmp/.trash/7031e4d0-d369-4a4d-afc4-f77eace1d257 3.051µs
```
Instead of something like this (testfile6 on g1n3, same version, the only difference is that the service was restarted)
```
2024-02-26T11:49:13.065 [OS] os.Rename g1n3:9018 /mnt/disk10/qa/test/testfile6/459d2bcb-e854-48b3-9488-34348f205715 -> /mnt/disk10/qa/.minio.sys/tmp/.trash/ee65ed74-be6d-4d6c-b1a7-fb62c866dad5 105.397µs
2024-02-26T11:49:13.065 [OS] os.Rename g1n3:9018 /mnt/disk10/qa/test/testfile6/xl.meta -> /mnt/disk10/qa/.minio.sys/tmp/.trash/b8ede1e4-6380-4136-b06c-74ac01af2a95 32.393µs
2024-02-26T11:49:13.065 [OS] os.Remove g1n3:9018 /mnt/disk10/qa/test/testfile6 45.703µs
```

## Steps to Reproduce (for bugs)

The hardest part to reproduce is the behavior where os.Remove calls are no longer made. For us it happened after a service lifetime of 5 days, in a distributed setup.
## Context

N/A

## Regression

N/A

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

```
minio version RELEASE.2024-02-17T01-15-57Z (commit-id=b6e98aed0161bb526aaf11fa1672d30eb89dca4b)
Runtime: go1.21.6 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.
```

An extract of the relevant MinIO parameters

```
MINIO_VOLUMES="https://g1n{1...12}:9018/mnt/disk3/qa https://g2n{1...12}:9018/mnt/disk5/qa https://g2n{1...12}:9018/mnt/disk13/qa https://g1n{1...12}:9018/mnt/disk5/qa https://g1n{1...12}:9018/mnt/disk10/qa"
GOGC=100
GOMEMLIMIT=7GiB

MINIO_API_LIST_QUORUM="optimal"
MINIO_DRIVE_MAX_TIMEOUT=15s
```

```
uname -a
Linux g1n1 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
@vdombrovski looks like you are making some wrong observations here. 

The issue is that you have partial delete in quorum but you have a `listing` that is doing `optimal` listing. 

It looks like some drives were disconnected and not reconnected yet, which caused some shards to be left over.

You should check how many shards are left over and also change your list quorum to be "strict".

**Comment by harshavardhana** [comment]
however yes os.Remove() must be called not sure why it wouldn't be called since it is at the lowest layer here and they are called recursively one over the other. 


like 

```
os.Rename(foo/data-dir -> tmp/.trash/uuid)
os.Rename(foo/xl.meta -> tmp/.trash/uuid)
os.Remove(foo/)
```

There is no reason that a caller would simply vanish here without doing os.Remove() it looks like some trace is missing here.

**Comment by vdombrovski** [comment]
@harshavardhana I can assure you no trace is missing, and the optimal quorum is a deliberate choice here, I'm not expecting a fully consistent listing during an outage (which isn't the case here). I can also perform a GET request on the object and I will get it back, as it is not deleted.

I haven't yet looked into where the os.Remove() is made from, but if I understand correctly, the os.Rename is synchronous with the call, while os.Remove is done elsewhere (possibly in a Goroutine, possibly using the I/O token quota?). Isn't this what the original PR was trying to fix?

**Comment by harshavardhana** [comment]
> @harshavardhana I can assure you no trace is missing, and the optimal quorum is a deliberate choice here, I'm not expecting a fully consistent listing during an outage (which isn't the case here). I can also perform a GET request on the object and I will get it back, as it is not deleted.
> 
> I haven't yet looked into where the os.Remove() is made from, but if I understand correctly, the os.Rename is synchronous with the call, while os.Remove is done elsewhere (possibly in a Goroutine, possibly using the I/O token quota?). Isn't this what the original PR was trying to fix?

No they are not all are local calls one after the other as I wrote in sequence. A rename() must have failed for a remove() to be not called.

And yes I can't also reproduce it either on multiple distributed server deployments.

So not sure what else can be done here to debug. I would suggest to get us some profiles or even deploy a binary with more debug statements.

Otherwise I can't see how it is even possible. Are your backend disks real mounts with real filesystems like XFS?

**Comment by vdombrovski** [comment]
Yes they are real XFS filesystems, mounted and accessed directly by MinIO (no LVM, default mount options). We are using physical machines as well.

> A rename() must have failed for a remove() to be not called

This is very interesting, maybe the rename() call isn't working for some reason (which explains why both Rename calls are duplicated?). I'll try to get some more traces. In the meantime, yesterday I have spinned up the 2024-02-26 release which includes the change you've made here #18801. I should have some more test results by the end of the week, this might help with the issue too.

> or even deploy a binary with more debug statements.
I will consider adding some more traces around the os.Rename and os.Remove calls and spinning the modified binary once I've gathered more logs.

**Comment by harshavardhana** [comment]
Thanks for all the help @vdombrovski

**Comment by vdombrovski** [comment]
@harshavardhana quick update: after only 48 hours of runtime, the version 2024-02-26 is having issues with delete requests.

I've included the full tracelog for a delete request for an existing object test / testfile3 below. I will continue searching why no os.Remove requests are done.

[minio-2024-02-26-delete-issue-19140.log](https://github.com/minio/minio/files/14432670/minio-2024-02-26-delete-issue-19140.log)

**Comment by vdombrovski** [comment]
@harshavardhana I think I found something. On a working instance, I do have a .trash directory:

```
ls -lah /mnt/disk15/local/.minio.sys/tmp/
total 0
drwxr-xr-x 3 root root  28 Feb 28 12:59 .
drwxr-xr-x 7 root root 126 Feb 28 12:58 ..
drwxr-xr-x 2 root root 126 Feb 28 12:58 .trash
```

However after some time (or in this case, maybe after a certain request), this trash directory is gone from all nodes:

```
/mnt/disk5/qa/.minio.sys/tmp/:
total 4.0K
drwxr-xr-x 2 root root   58 Feb 28 13:01 .
drwxr-xr-x 7 root root  126 Feb 26 13:33 ..
-rw-r--r-- 1 root root 2.1K Feb 28 02:32 dd6eb982-94b9-4971-9ed9-9eef23f745aa
```

Restoring this directory on a node leads to a successful Remove call. Of course I would have to do it on all nodes of the target server pool to actually delete the object:

```
mc admin trace demo1 --all | grep testfile3  | grep -i remove
2024-02-28T13:07:23.496 [OS] os.Remove g1n12:9018 /mnt/disk5/qa/test/testfile3 41.848µs
```

Fixing it would imply either finding what's deleting this directory (scanner, healer, some S3 request...), or adding an extra check to restore the .trash directory before the os.Rename (that would mean extra disk I/O on deletes however).

**Comment by harshavardhana** [comment]
Oh, I see now a `.trash` folder is removed, leading to `os.Rename()` failures.

**Comment by harshavardhana** [comment]
The rename is supposed to recreate the parent folders; not sure why it's not doing that.

**Comment by harshavardhana** [comment]
@vdombrovski please try this patch and let us know how it goes. https://github.com/minio/minio/pull/19155

**Comment by vdombrovski** [comment]
@harshavardhana thank you; The patch is now live on our QA instance, as before I will let it run for ~48hours at least to check whether the issue is fixed. Will keep you posted.

**Comment by harshavardhana** [comment]
Thank you @vdombrovski

**Comment by xpader** [comment]
I have seen same problem before after recreate minio container, but problem gone after restart container.

**Comment by harshavardhana** [comment]
@vdombrovski checking back to see if the problem is happening or not?

**Comment by harshavardhana** [comment]
Closing this since I haven't heard back from you in the last 4 days. Assuming this is resolved.

**Comment by vdombrovski** [comment]
Hello @harshavardhana, just to let you know, this is now resolved, as confirmed by the long-running test. Thank you for your help and reactivity.

**Comment by gjaekel** [comment]
@harshavardhana: We also stepped into this issue.

It is not fixed using `minio version RELEASE.2024-02-09T21-25-16Z (commit-id=997ba3a5742cd0ebacfa109cd93faba67e4c5036)`. I re-created the missing trash directory four days ago which restores the functionality of the DELETE operation. But unfortunately I found today that  it disappeared just after two days, again.

We become aware this issue about a week before, but it happens about three month before. It just appear on our production stage, but not on two others (CI-testing and approval). And over the time it sums up to more than 1M of unremoved object directories (and it content) flat at one parent directory. A day before the issue we changed from `RELEASE.2023-11-20T22-40-07Z` to `RELEASE.2024-02-09T21-25-16Z`

Today, I fixed the missing directory, again and switched to `minio version RELEASE.2024-05-01T01-11-10Z (commit-id=7926401cbd5cceaacd9509f2e50e1f7d636c2eb8`. We'll see if the bug is fixed with this.
