### ISSUE TITLE
Pushing a local Docker image to the DTR fails.

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4873]
Filing for Makersphere.
## Expected Behavior
When using Minio instead of AWS S3 as a storage backend for Docker Trusted Registry (part of Docker EE),
all Docker images that get pushed from clients to the registy, get stored in a configured bucket on Minio.
If the Minio Browser is enabled, you can inspect these images in the bucket.
The Docker CLI will report no errors.

## Current Behavior
Pushing a local Docker image (on a developer's machine) to the DTR fails with the following error:

```❯ docker push dtr.example.org/devops/hello-world:latest
The push refers to a repository [dtr.example.org/devops/hello-world]
45761469c965: Pushing [==================================================>]  3.584kB
received unexpected HTTP status: 500 Internal Server Error```

Inspecting the logs of the DTR container reveals that some kind of path is missing:

```{
"auth.user.name":"f4864fbd-b578-43a7-8464-ce71ccbee777",
"go.version":"go1.7.4",
"http.request.host":"dtr.example.org",
"http.request.id":"3b1d1101-443b-4761-998d-7a116b74cfcf",
"http.request.method":"PATCH",
"http.request.remoteaddr":"10.xxx.xx.x",
"http.request.uri":"/v2/devops/hello-world/blobs/uploads/4e1ee261-5732-445b-b503-5f66ab08ce96?_state=Ufd56_wRIko-Ej1_1z5MzAUSi3zPylUHN5GAvyj_w8V7Ik5hbWUiOiJkZXZvcHMvaGVsbG8td29ybGQiLCJVVUlEIjoiNGUxZWUyNjEtNTczMi00NDViLWI1MDMtNWY2NmFiMDhjZTk2IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE3LTA4LTMwVDE2OjUxOjExLjA0NjExNDM1WiJ9",
"http.request.useragent":"docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.9.41-moby os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(darwin\\))",
"level":"error",
"msg":"error resolving upload: s3aws: Path not found: /docker/registry/v2/repositories/devops/hello-world/_uploads/4e1ee261-5732-445b-b503-5f66ab08ce96/data",
"time":"2017-08-30T16:51:11.548830658Z",
"vars.name":"devops/hello-world",
"vars.uuid":"4e1ee261-5732-445b-b503-5f66ab08ce96"
}
```
## Possible Solution
It's not clear why this `[...]/data` directory is missing and according to Docker, it could be an issue with the S3 protocol implantation.

##  Steps to Reproduce
1. Install `docker/dtr:2.3.2` (with a trial license)
2. Install `minio/minio:RELEASE.2017-08-05T00-00-53Z` on a different node
3. Add Minio as storage backend, _Settings > Storage_
4. Setup a repository for `<DTR USER>/hello-world`, _Repositories > New repository_
5. On a client machine, login with `docker login <DTR URL>`
6. Pull the `hello-world:latest` image from Docker Hub
7. Tag it with `docker tag hello-world:latest <DTR URL>/<DTR USER>/hello-world:latest`
8. Push the image with `docker push <DTR URL>/<DTR USER>/hello-world:latest`
9. Docker CLI returns a `500` error

##  Context
We're just trying to store our Docker images on Minio. :)

##  Your Environment
* Version used (`minio version`):

`minio/minio:RELEASE.2017-08-05T00-00-53Z`

* Environment name and version (Docker):
```
Containers: 7
 Running: 3
 Paused: 0
 Stopped: 4
Images: 4
Server Version: 17.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 26
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: [redacted]
 Is Manager: false
 Node Address: 10.xxx.x.xxx
 Manager Addresses:
  10.xxx.xx.xx:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-92-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.771GiB
Name: [redacted]
ID: [redacted]
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
* Operating System and version (`uname -a`):

`Linux [redacted] 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by deekoder** [comment]
Related https://github.com/minio/minio/issues/4779

**Comment by deekoder** [comment]
works with `minio/minio:RELEASE.2017-07-24T18-27-35Z`

**Comment by donatello** [comment]
The DTR issue is because list-multipart-uploads has been changed to return empty list with PR https://github.com/minio/minio/pull/4694 and issue https://github.com/minio/minio/issues/4564

This was confirmed by setting up a DTR server and capturing the network traffic between the DTR server and the Minio storage server. The raw capture is [here](https://pastebin.com/8sGyQ5TW).

**Comment by mpepping** [comment]
Having this issue with minio version `2017-08-05T00:00:53Z`. Using Docker DTR 2.2 and configured S3-storage without TLS. Minio is running native.
Can confim it does work OK with the `2017-07-24T18-27-35Z` release of minio, as mentioned by @deekoder.

**Comment by xinfengliu** [comment]
I also use Minio 2017-08-05T00:00:53Z and DTR 2.3.2, and push images without issues. The differences are: I use docker engine 17.06.1-ee-2, and I run Minio (distributed mode) on host OS rather than in container.

**Comment by deekoder** [comment]
This is fixed with the latest Minio release. Please let us know if this works well.

**Comment by surajpasuparthy** [comment]
using minio 2017-08-05T00:00:53Z and i still have the same problem.
Running the mino deployment on kubernetes. local storage for docker works. but the minio throws this error:
 level=error msg="error resolving upload: s3aws: Path not found: /docker/registry/v2/repositories/kubernetes/pause/_uploads/14de907d-94d6-4027-b24c-d796f949da23/data" environment=staging go.version=go1.7.6 http.request.host=aw10-minnie-2.corp.airwave.com http.request.id=4e55d383-ef2e-4a98-bf08-328a11a6357c http.request.method=PATCH http.request.remoteaddr=10.2.3.1 http.request.uri="/v2/kubernetes/pause/blobs/uploads/14de907d-94d6-4027-b24c-d796f949da23?_state=vEt6L3IztyOvVY-DD3WDwr0-1VrVBE2BVgRL3G5HRdF7Ik5hbWUiOiJrdWJlcm5ldGVzL3BhdXNlIiwiVVVJRCI6IjE0ZGU5MDdkLTk0ZDYtNDAyNy1iMjRjLWQ3OTZmOTQ5ZGEyMyIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNy0xMS0yMVQyMToxOToyMi41Mjk0ODU3NTdaIn0%3D" http.request.useragent="docker/1.12.6 go/go1.7.5 git-commit/a82d35e kernel/4.11.9-coreos os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))" instance.id=ae04ddda-1898-4143-9049-7bbf54992a59 service=registry vars.name="kubernetes/pause" vars.uuid=14de907d-94d6-4027-b24c-d796f949da23 version=v2.6.2 

any ideas?
