### ISSUE TITLE
Minio returns "The specified bucket is not valid"

### ISSUE THREAD

**Issue by ItalyPaleAle** [minio/minio#4948]
Background: I have been using Minio Gateway to Azure to backup my laptop using [Arq 5](https://www.arqbackup.com/).

After working flawlessly for a very long time, suddenly a month ago Minio stopped working. When Arq tries to list files, it gets an error saying "The specified bucket is not valid". This is the URL requested:

`https://minio.lacasetta.xyz/alessandro-mbp-arq/?prefix=3FA96B40-45FA-40D1-B03C-6176D84383AD/packsets/F4D40593-98FA-4ACF-AA22-767FC14B3CCE-trees/&delimiter=/&marker=3FA96B40-45FA-40D1-B03C-6176D84383AD/packsets/F4D40593-98FA-4ACF-AA22-767FC14B3CCE-trees/d9fb3d4ca39de9a43c5c6221d9b3b3d412157b30.pack`

(Note: the DNS name is internal in my LAN only, so it won't work here).

The file is there: using the Minio browser, I can see that in the bucket `alessandro-mbp-arq` the file `3FA96B40-45FA-40D1-B03C-6176D84383AD/packsets/F4D40593-98FA-4ACF-AA22-767FC14B3CCE-trees/d9fb3d4ca39de9a43c5c6221d9b3b3d412157b30.pack` does exist. The file also exists on Azure.

I am not sure why Minio would return this weird error, at this point. The "folder" in which the file is located is fairly large, with 606 files. Also, there are lots of files in the bucket.

I'm running Minio via Docker, using the latest tag (latest release).

Everything on the Azure Account is encrypted (end-to-end), so if you're interested in having the key to try replicating the issue please reach out to me!

## Expected Behavior
Minio should return a valid answer and not an error.

## Current Behavior
Minio responds with "The specified bucket is not valid"

## Steps to Reproduce (for bugs)
I'm running Minio via Docker with the following Compose file:

```
version: '3.1'

services:
  minio-gateway:
    image: minio/minio:latest
    command: 'gateway azure --address :443'
    networks:
      containernet:
        ipv4_address: 10.3.2.2
    restart: always
    ports:
      - '443:443'
    secrets:
      - access_key
      - secret_key
    volumes:
      - /etc/minio:/root/.minio

secrets:
   access_key:
     file: /etc/docker-secrets/minio-gateway/access_key.txt
   secret_key:
     file: /etc/docker-secrets/minio-gateway/secret_key.txt

networks:
  containernet:
    external:
      name: containernet
```

Then use Arq to backup my laptop.

Minio reports this in its logs:

````
time="2017-09-21T01:20:17Z" level=error msg="Unable to list objects." cause="Bucket name invalid: alessandro-mbp-arq" source="[gateway-handlers.go:723:gatewayAPIHandlers.ListObjectsV1Handler()]" stack="gateway-azure.go:266:(*azureObjects).ListObjects gateway-handlers.go:714:(GatewayLayer).ListObjects-fm gateway-handlers.go:721:gatewayAPIHandlers.ListObjectsV1Handler gateway-router.go:107:(gatewayAPIHandlers).ListObjectsV1Handler-fm"
````

Please let me know if you'd like the access keys to the Azure Storage Account.

**Comment by krishnasrinivas** [comment]
@EgoAleSum Can you compile Minio from this branch and send us the log:
https://github.com/krishnasrinivas/minio/tree/azure-list-debug

**Comment by ItalyPaleAle** [comment]
Do you have a document explaining how to compile this and package it into a Docker container? Thanks

**Comment by krishnasrinivas** [comment]
Can you `docker pull krishnasrinivas/minio` and check? It has the needed changes

**Comment by ItalyPaleAle** [comment]
This is what I see (nothing different):

```
ship:~# docker ps -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS               NAMES
98de59f2f086        krishnasrinivas/minio:latest   "/usr/bin/docker-e..."   3 seconds ago       Up 3 seconds                            boot_minio-gateway_1
ship:~# docker logs -f boot_minio-gateway_1

Endpoint:  https://10.3.2.2  https://127.0.0.1
AccessKey: lacasettaback 
SecretKey: XXXX

Browser Access:
   https://10.3.2.2  https://127.0.0.1

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myazure https://10.3.2.2 lacasettaback XXXX

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

time="2017-09-25T19:42:15Z" level=error msg="Unable to list objects." cause="Bucket name invalid: alessandro-mbp-arq" source="[gateway-handlers.go:732:gatewayAPIHandlers.ListObjectsV1Handler()]" stack="gateway-azure.go:320:(*azureObjects).ListObjects gateway-handlers.go:723:(GatewayLayer).ListObjects-fm gateway-handlers.go:730:gatewayAPIHandlers.ListObjectsV1Handler gateway-router.go:107:(gatewayAPIHandlers).ListObjectsV1Handler-fm" 
time="2017-09-25T19:42:17Z" level=error msg="Unable to list objects." cause="Bucket name invalid: alessandro-mbp-arq" source="[gateway-handlers.go:732:gatewayAPIHandlers.ListObjectsV1Handler()]" stack="gateway-azure.go:320:(*azureObjects).ListObjects gateway-handlers.go:723:(GatewayLayer).ListObjects-fm gateway-handlers.go:730:gatewayAPIHandlers.ListObjectsV1Handler gateway-router.go:107:(gatewayAPIHandlers).ListObjectsV1Handler-fm" 
time="2017-09-25T19:42:19Z" level=error msg="Unable to list objects." cause="Bucket name invalid: alessandro-mbp-arq" source="[gateway-handlers.go:732:gatewayAPIHandlers.ListObjectsV1Handler()]" stack="gateway-azure.go:320:(*azureObjects).ListObjects gateway-handlers.go:723:(GatewayLayer).ListObjects-fm gateway-handlers.go:730:gatewayAPIHandlers.ListObjectsV1Handler gateway-router.go:107:(gatewayAPIHandlers).ListObjectsV1Handler-fm" 
time="2017-09-25T19:42:47Z" level=error msg="Unable to list objects." cause="Bucket name invalid: alessandro-mbp-arq" source="[gateway-handlers.go:732:gatewayAPIHandlers.ListObjectsV1Handler()]" stack="gateway-azure.go:320:(*azureObjects).ListObjects gateway-handlers.go:723:(GatewayLayer).ListObjects-fm gateway-handlers.go:730:gatewayAPIHandlers.ListObjectsV1Handler gateway-router.go:107:(gatewayAPIHandlers).ListObjectsV1Handler-fm" 
```

**Comment by krishnasrinivas** [comment]
Sorry, can you try this image @egoalesum `krishnasrinivas/minio:azure-list-debug`

**Comment by ItalyPaleAle** [comment]
Still nothing new:

````
time="2017-09-26T00:35:00Z" level=error msg="Unable to list objects." cause="Bucket name invalid: alessandro-mbp-arq" source="[gateway-handlers.go:732:gatewayAPIHandlers.ListObjectsV1Handler()]" stack="gateway-azure.go:320:(*azureObjects).ListObjects gateway-handlers.go:723:(GatewayLayer).ListObjects-fm gateway-handlers.go:730:gatewayAPIHandlers.ListObjectsV1Handler gateway-router.go:107:(gatewayAPIHandlers).ListObjectsV1Handler-fm" 
````

**Comment by krishnasrinivas** [comment]
That is weird. I am trying to avoid getting your access/secret keys. Can you try this one last time, use this binary: http://krisupload.s3-us-west-2.amazonaws.com/minio-public/minio.alessandro (linux binary) and see if you can get the log?

**Comment by ItalyPaleAle** [comment]
Sorry to bother you Krishna, but any chance you could package that into a Docker container?

**Comment by krishnasrinivas** [comment]
@EgoAleSum can you do `docker pull krishnasrinivas/minio:latest` again and check?

**Comment by ItalyPaleAle** [comment]
@krishnasrinivas  here it is, finally with a clear error message (or so it seems to me):

`````
ship:~# docker ps -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS               NAMES
25062289045d        krishnasrinivas/minio:latest   "/usr/bin/docker-e..."   3 seconds ago       Up 2 seconds                            boot_minio-gateway_1
ship:~# docker logs -f boot_minio-gateway_1

Endpoint:  https://10.3.2.2  https://127.0.0.1
AccessKey: lacasettaback 
SecretKey: XXXX

Browser Access:
   https://10.3.2.2  https://127.0.0.1

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myazure https://10.3.2.2 lacasettaback XXXX

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

ListObjects Debug: bucket=alessandro-mbp-arq, prefix=3FA96B40-45FA-40D1-B03C-6176D84383AD/buckets/, marker=, delimiter=/, maxKeys=500, err=nil
ListObjects Debug: bucket=alessandro-mbp-arq, prefix=3FA96B40-45FA-40D1-B03C-6176D84383AD/buckets/, marker=, delimiter=/, maxKeys=500, err=nil
ListObjects Debug: bucket=alessandro-mbp-arq, prefix=3FA96B40-45FA-40D1-B03C-6176D84383AD/packsets/F4D40593-98FA-4ACF-AA22-767FC14B3CCE-blobs/, marker=, delimiter=/, maxKeys=500, err=nil
ListObjects Debug: bucket=alessandro-mbp-arq, prefix=3FA96B40-45FA-40D1-B03C-6176D84383AD/packsets/F4D40593-98FA-4ACF-AA22-767FC14B3CCE-blobs/, marker=3FA96B40-45FA-40D1-B03C-6176D84383AD/packsets/F4D40593-98FA-4ACF-AA22-767FC14B3CCE-blobs/5027c75001b682b187ec95b760d708860dad2409.pack, delimiter=/, maxKeys=500, err=storage: service returned error: StatusCode=400, ErrorCode=InvalidQueryParameterValue, ErrorMessage=Value for one of the query parameters specified in the request URI is invalid.
RequestId:e4b5a94c-001e-0064-4ee1-370995000000
Time:2017-09-27T22:40:55.3395190Z, RequestId=e4b5a94c-001e-0064-4ee1-370995000000, QueryParameterName=marker, QueryParameterValue=3FA96B40-45FA-40D1-B03C-6176D84383AD/packsets/F4D40593-98FA-4ACF-AA22-767FC14B3CCE-blobs/5027c75001b682b187ec95b760d708860dad2409.pack
time="2017-09-27T22:40:55Z" level=error msg="Unable to list objects." cause="Bucket name invalid: alessandro-mbp-arq" source="[gateway-handlers.go:732:gatewayAPIHandlers.ListObjectsV1Handler()]" stack="gateway-azure.go:325:(*azureObjects).ListObjects gateway-handlers.go:723:(GatewayLayer).ListObjects-fm gateway-handlers.go:730:gatewayAPIHandlers.ListObjectsV1Handler gateway-router.go:107:(gatewayAPIHandlers).ListObjectsV1Handler-fm" 
ListObjects Debug: bucket=alessandro-mbp-arq, prefix=3FA96B40-45FA-40D1-B03C-6176D84383AD/deletedbuckets/, marker=, delimiter=/, maxKeys=500, err=nil
ListObjects Debug: bucket=alessandro-mbp-arq, prefix=3FA96B40-45FA-40D1-B03C-6176D84383AD/packsets/F4D40593-98FA-4ACF-AA22-767FC14B3CCE-trees/, marker=, delimiter=/, maxKeys=500, err=nil
ListObjects Debug: bucket=alessandro-mbp-arq, prefix=3FA96B40-45FA-40D1-B03C-6176D84383AD/packsets/F4D40593-98FA-4ACF-AA22-767FC14B3CCE-trees/, marker=3FA96B40-45FA-40D1-B03C-6176D84383AD/packsets/F4D40593-98FA-4ACF-AA22-767FC14B3CCE-trees/d9fb3d4ca39de9a43c5c6221d9b3b3d412157b30.pack, delimiter=/, maxKeys=500, err=storage: service returned error: StatusCode=400, ErrorCode=InvalidQueryParameterValue, ErrorMessage=Value for one of the query parameters specified in the request URI is invalid.
RequestId:b2b68611-001e-00b0-0ee1-37b9c4000000
Time:2017-09-27T22:40:56.6379335Z, RequestId=b2b68611-001e-00b0-0ee1-37b9c4000000, QueryParameterName=marker, QueryParameterValue=3FA96B40-45FA-40D1-B03C-6176D84383AD/packsets/F4D40593-98FA-4ACF-AA22-767FC14B3CCE-trees/d9fb3d4ca39de9a43c5c6221d9b3b3d412157b30.pack
time="2017-09-27T22:40:56Z" level=error msg="Unable to list objects." cause="Bucket name invalid: alessandro-mbp-arq" source="[gateway-handlers.go:732:gatewayAPIHandlers.ListObjectsV1Handler()]" stack="gateway-azure.go:325:(*azureObjects).ListObjects gateway-handlers.go:723:(GatewayLayer).ListObjects-fm gateway-handlers.go:730:gatewayAPIHandlers.ListObjectsV1Handler gateway-router.go:107:(gatewayAPIHandlers).ListObjectsV1Handler-fm" 
ListObjects Debug: bucket=alessandro-mbp-arq, prefix=3FA96B40-45FA-40D1-B03C-6176D84383AD/packsets/F4D40593-98FA-4ACF-AA22-767FC14B3CCE-trees/, marker=, delimiter=/, maxKeys=500, err=nil
ListObjects Debug: bucket=alessandro-mbp-arq, prefix=3FA96B40-45FA-40D1-B03C-6176D84383AD/packsets/F4D40593-98FA-4ACF-AA22-767FC14B3CCE-trees/, marker=3FA96B40-45FA-40D1-B03C-6176D84383AD/packsets/F4D40593-98FA-4ACF-AA22-767FC14B3CCE-trees/d9fb3d4ca39de9a43c5c6221d9b3b3d412157b30.pack, delimiter=/, maxKeys=500, err=storage: service returned error: StatusCode=400, ErrorCode=InvalidQueryParameterValue, ErrorMessage=Value for one of the query parameters specified in the request URI is invalid.
RequestId:d4ac520c-001e-0026-1ee1-37b015000000
Time:2017-09-27T22:41:05.7362278Z, RequestId=d4ac520c-001e-0026-1ee1-37b015000000, QueryParameterName=marker, QueryParameterValue=3FA96B40-45FA-40D1-B03C-6176D84383AD/packsets/F4D40593-98FA-4ACF-AA22-767FC14B3CCE-trees/d9fb3d4ca39de9a43c5c6221d9b3b3d412157b30.pack
time="2017-09-27T22:41:04Z" level=error msg="Unable to list objects." cause="Bucket name invalid: alessandro-mbp-arq" source="[gateway-handlers.go:732:gatewayAPIHandlers.ListObjectsV1Handler()]" stack="gateway-azure.go:325:(*azureObjects).ListObjects gateway-handlers.go:723:(GatewayLayer).ListObjects-fm gateway-handlers.go:730:gatewayAPIHandlers.ListObjectsV1Handler gateway-router.go:107:(gatewayAPIHandlers).ListObjectsV1Handler-fm" 
`````

**Comment by krishnasrinivas** [comment]
Thanks @EgoAleSum 
Azure expects `marker` (https://docs.microsoft.com/en-us/rest/api/storageservices/List-Blobs?redirectedfrom=MSDN) in the ListBlobs request to be the `nextmarker` field of the previous ListBlobs result.

The marker is an opaque value.

Arq 5, does not use Azure's ListBlobs result for the marker and uses the object name directly (which is allowed in the S3 protocol)

We'll discuss how we can fix this.

**Comment by harshavardhana** [comment]
> Arq 5, does not use Azure's ListBlobs result for the marker and uses the object name directly (which is allowed in the S3 protocol)
> 
> We'll discuss how we can fix this.

Setting this as blocked for further discussion

**Comment by jmaitrehenry** [comment]
I had the same problem with s3cmd:
```
minio_static.2.y5hltewnxev3@vm-mon-docker0    | Time:2017-10-10T20:49:05.3628668Z, RequestInitiated=Tue, 10 Oct 2017 20:49:04 GMT, RequestId=46edf168-001e-0027-1509-4220d4000000, API Version=2016-05-31, QueryParameterName=marker, QueryParameterValue=xxx/yyyy/zzz
```
Where `xxx/yyyy/zzz` is the object name

s3cmd use the marker for syncing local  directory and remote "directory" and checking the md5 of the files

**Comment by ItalyPaleAle** [comment]
@jmaitrehenry since this is about s3cmd, can you please try a new build of s3cmd and minio, as per this thread? https://github.com/s3tools/s3cmd/issues/880#issuecomment-335441856 (check the linked comment and all the ones after)

**Comment by jmaitrehenry** [comment]
@EgoAleSum I already have a fix ready to push to s3cmd, I use this issue as a reference
But it's not related to https://github.com/s3tools/s3cmd/issues/880#issuecomment-335441856, I will open an another issue in s3cmd related to Mark/NextMark

**Comment by balamurugana** [comment]
On LIstObjectV1, marker can be any existing object name.  When user wants to list objects with marker freshly (Not from beginning), currently there is no way in `ListBlobs()` to do the listing at specified marker.

Solution could be to use `ListBlobs()` from beginning and skip till we reach user specified marker and return the result.  This way we could remember `ContinuationToken` for the given marker.

**Comment by harshavardhana** [comment]
@krishnasrinivas can this be closed?

**Comment by ItalyPaleAle** [comment]
I don't believe the issue has been fixed.

**Comment by deekoder** [comment]
We will look into it. I mistakenly thought s3cmd may have fixed this issue. Now I see the issue is still happening. So it may be on our end. We will look into this @EgoAleSum

**Comment by krishnasrinivas** [comment]
@EgoAleSum the fix for this is merged into master

**Comment by ItalyPaleAle** [comment]
Thank you! As soon as the new Minio is released I’ll be happy to try this out.

**Comment by deekoder** [comment]
Please let us know if it works for you.

**Comment by ItalyPaleAle** [comment]
I will try it once the new release of Minio comes out. However, please note that last time it took a few weeks/months before the issue appeared (I guess Arq does that only when there's lots of data already).
