### ISSUE TITLE
Objects which lost majority should be removed in the object list

### ISSUE THREAD

**Issue by Vesnica** [minio/minio#5733]
## Steps to Reproduce

1. Create a 3X2 cluster (3 nodes, 2 disks each)
2. Create test bucket and upload some folder and files to it
3. `mc ls --recursive local/test | wc -l` gives consistent result
4. On 1 node, execute`rm -rf` to remove 1 folder from 2 disks
5. `mc ls --recursive local/test | wc -l` still gives the consistent result
6. `mc cp --recursive local/test/removed_folder .` can download the folder successfully
7. On another node, execute`rm -rf` to remove the same folder from 2 disks (this folder now lost its majority)

## Expected Behavior

`mc ls local/test/removed_folder/` should not list the removed folder and it's content

## Current Behavior

`mc ls local/test/removed_folder/` still list the removed folder and its content, and mc gives the following error(after a long wait) when user trying to access one of them:
```
mc: <ERROR> Unable to list folder. Multiple disk failures, unable to reconstruct data.
```

## Possible Solution

On the last node, use `rm -rf` to remove the folder on 2 disks, now `mc ls local/test` will not show the removed folder

## Context

If some object is lost its majority, maybe minio should not list it to the user, because many user or applications will try to access it if they can see it. and a final error will frustrate the user or make some procedure to fail (Again, docker registry garbage collect)

## Your Environment

* Version used (`minio version`): RELEASE.2018-03-28T23-45-53Z
* Operating System and version (`uname -a`): Linux NIV-AI 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> mc ls local/test/removed_folder/ still list the removed folder and its content, and mc gives the following error(after a long wait) when user trying to access one of them:

can you provide the partial output that you see would like to see what is being listed we fixed this in 

```
commit 2afd196c83ceccaa930dff74ed052432bfdcdecf
Author: Krishna Srinivas <krishna@minio.io>
Date:   Thu Feb 1 10:47:49 2018 -0800

    Quorum based listing for XL (#5475)
    
    fixes #5380
```

**Comment by Vesnica** [comment]
I create a registry which mounts on minio and then pushes 2 images to it:
```
./mc ls local/docker/docker/registry/v2/repositories/
[2018-03-29 15:21:49 CST]     0B cuda/
[2018-03-29 15:21:49 CST]     0B rust/
```
Then I remove the cuda folder from 4 disks which on 2 nodes:
```
# On node 1
sudo rm -rf data_1/docker/docker/registry/v2/repositories/cuda/
sudo rm -rf data_2/docker/docker/registry/v2/repositories/cuda/

# On node 2
sudo rm -rf data_1/docker/docker/registry/v2/repositories/cuda/
sudo rm -rf data_2/docker/docker/registry/v2/repositories/cuda/
```
I can still see the cuda folder by `mc ls`:
```
./mc ls local/docker/docker/registry/v2/repositories/
[2018-03-29 15:23:22 CST]     0B cuda/
[2018-03-29 15:23:22 CST]     0B rust/
```
And even some sub-folders in cuda:
```
./mc ls local/docker/docker/registry/v2/repositories/cuda/
[2018-03-29 15:23:33 CST]     0B _layers/
[2018-03-29 15:23:33 CST]     0B _manifests/

./mc ls local/docker/docker/registry/v2/repositories/cuda/_layers/sha256
[2018-03-29 15:23:49 CST]     0B 0197606d83b91dcbcb6339c6279c6e3684157a39cfefd4f0296a76b61c18f1c8/
[2018-03-29 15:23:49 CST]     0B 07b6d2ffca98c19523e57afcb768213703742577bc90622a0cf13f123e6ba62b/
[2018-03-29 15:23:49 CST]     0B 145c1bf7947adf36380293a0aefe12010d0069cd562adac725a48bab13db7d1d/
[2018-03-29 15:23:49 CST]     0B 2f25d8d1d05863dda0bf7565e124cc34ceefa2121477e82477e3ab8dd6b8e1ca/
[2018-03-29 15:23:49 CST]     0B 32c9b09af4bc8bdd3c49d9d14dad7fa6e2d3399beee51d93f15571e3108f3f43/
[2018-03-29 15:23:49 CST]     0B 71402a4f9aedbdd6d83c0e052f0c0167fb56f0461870ef00f2cf9d586b8ce5ac/
[2018-03-29 15:23:49 CST]     0B 82f7e591c3e9f0bafaf03fa0747b48d8422b4b37f2b55ea5d86e0691d4563f79/
[2018-03-29 15:23:49 CST]     0B 87bfe0d2f0e856e078c4490bcf687026260e30cb7c1a2b20060516cae770f179/
[2018-03-29 15:23:49 CST]     0B cae975da6d2a9987d4cd1ce432b3c83696d7d842bdf7228834967a46c3a462dc/
[2018-03-29 15:23:49 CST]     0B de3b7b86b94fee45ccb2063278144555d6164fa5c22f252175394e3424c87d44/
[2018-03-29 15:23:49 CST]     0B f2233041f5574e65c885bc8487b3da6deb93ea5c6061cce3d047d098d9a17d78/
[2018-03-29 15:23:49 CST]     0B f321bcc6a76c4e4f27bd249bcb75a84279b6783cbb8a44c5a346d1f254d3406c/
```
But it fails (after a long timeout waiting) when I try to access the final object:
```
./mc ls local/docker/docker/registry/v2/repositories/cuda/_layers/sha256/f321bcc6a76c4e4f27bd249bcb75a84279b6783cbb8a44c5a346d1f254d3406c/
mc: <ERROR> Unable to list folder. Multiple disk failures, unable to reconstruct data.
```
What I expect to see is like this:
```
./mc ls local/docker/docker/registry/v2/repositories/
[2018-03-29 16:40:50 CST]     0B rust/
```

**Comment by harshavardhana** [comment]
> But it fails (after a long timeout waiting) when I try to access the final object:
> 
> ./mc ls local/docker/docker/registry/v2/repositories/cuda/_layers/sha256/f321bcc6a76c4e4f27bd249bcb75a84279b6783cbb8a44c5a346d1f254d3406c/
> mc: <ERROR> Unable to list folder. Multiple disk failures, unable to reconstruct data.
> What I expect to see is like this:
> 
> ./mc ls local/docker/docker/registry/v2/repositories/
> [2018-03-29 16:40:50 CST]     0B rust/

Folders are replicated across all servers @Vesnica its only objects which can indicate to us that they have lost quorum, so perhaps that is the reason you might still see these directories. But do they cause issues to docker registry? if yes in what way can you explain? 

> But it fails (after a long timeout waiting) when I try to access the final object:

This is because `mc ls` is retrying for the reply from the server i.e HTTP StatusCode 503 (quorum loss) so it is an expected behavior of `mc ls` - if you simply did List object call yourself through the API you would see an error without the retry delay.

**Comment by Vesnica** [comment]
After some test, I found that include the problematic objects in the list will render docker registry unusable (not only the garbage collection), here is the reproduce steps:

1. Recreate the same minio cluster and registry
2. Push 2 images to the registry
3. Registry's list image api working properly:

    ```
    curl http://127.0.0.1:5000/v2/_catalog
    {"repositories":["cockroachdb","prom"]}
    ```
4. On 2 nodes, use `rm` to remove the cockroachdb repo folder:
    ```
    sudo rm -rf data_1/docker/docker/registry/v2/repositories/cockroachdb/
    sudo rm -rf data_2/docker/docker/registry/v2/repositories/cockroachdb/
    ```
5. Registry's list image api is broken now:
    ```
    curl http://127.0.0.1:5000/v2/_catalog
    {"errors":[{"code":"UNKNOWN","message":"unknown error","detail":{"DriverName":"s3aws","Enclosed":{"awsError":{}}}}]}
    ```
6. But if I remove the cockroachdb repo folder on the last node, registry works again:
    ```
    # On last node
    sudo rm -rf data_1/docker/docker/registry/v2/repositories/cockroachdb/
    sudo rm -rf data_2/docker/docker/registry/v2/repositories/cockroachdb/

    curl http://127.0.0.1:5000/v2/_catalog
    {"repositories":["prom"]}
    
    ```
Registry logs:
```
127.0.0.1 - - [30/Mar/2018:01:54:30 +0000] "GET /v2/_catalog HTTP/1.1" 200 40 "" "curl/7.47.0"
ERRO[0825] response completed with error                 err.code=unknown err.detail=s3aws: XMinioReadQuorum: Multiple disk failures, unable to reconstruct data.
        status code: 503, request id: 15208FE620C4F26A err.message=unknown error go.version=go1.7.6 http.request.host=127.0.0.1:5000 http.request.id=0869fb1f-a814-42e4-8cd5-c111f1419154 http.request.method=GET http.request.remoteaddr=127.0.0.1:59842 http.request.uri=/v2/_catalog http.request.useragent=curl/7.47.0 http.response.contenttype=application/json; charset=utf-8 http.response.duration=4.369609614s http.response.status=500 http.response.written=117 instance.id=167c59d9-3320-4885-9b74-d98f89d0196b service=registry version=v2.6.2
127.0.0.1 - - [30/Mar/2018:01:54:48 +0000] "GET /v2/_catalog HTTP/1.1" 500 117 "" "curl/7.47.0"
127.0.0.1 - - [30/Mar/2018:01:56:56 +0000] "GET /v2/_catalog HTTP/1.1" 200 26 "" "curl/7.47.0"
```
Registry config.yml:
```
version: 0.1
log:
  level: warn
  fields:
    service: registry
storage:
  s3:
    accesskey: ACCESSKEY
    secretkey: SECRETKEY
    region: us-east-1
    regionendpoint: http://localhost:9000
    bucket: docker
    secure: false
    v4auth: true
    chunksize: 5242880
  delete:
    enabled: true
  redirect:
    disable: true
http:
  addr: :5000
  secret: SECRET
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: false
    interval: 10s
    threshold: 3
```
Minio doesn't produce any error logs

**Comment by Vesnica** [comment]
My point is: minio should only expose those currently available objects to the user, otherwise the user will have to do error checking and exception handling before using each object, which is sometimes difficult to achieve.

**Comment by harshavardhana** [comment]
> My point is: minio should only expose those currently available objects to the user, otherwise the user will have to do error checking and exception handling before using each object, which is sometimes difficult to achieve.

Agreed sent a PR. @Vesnica
