### ISSUE TITLE
API: ListObjectsV1: error file access denied

### ISSUE THREAD

**Issue by cmdrrobin** [minio/minio#5902]
When uploading Docker images to the registry I get the following message:

`error parsing HTTP 403 response body: unexpected end of JSON input: ""`

When checking the Minio logs I see the following errors:

```
PI: ListObjectsV1(bucket=docker-registry)
Time: 08:59:17 UTC 05/08/2018
RemoteHost: 10.44.96.7:51634
UserAgent: aws-sdk-go/1.1.0 (go1.6.4; linux; amd64)
Error: file access denied
       1: cmd/fs-v1-helpers.go:222:cmd.fsStatDir()
       2: cmd/fs-v1.go:566:cmd.(*FSObjects).getObjectInfo()
       3: cmd/fs-v1.go:1009:cmd.(*FSObjects).ListObjects.func1()
       4: cmd/fs-v1.go:1046:cmd.(*FSObjects).ListObjects()
       5: cmd/bucket-handlers-listobjects.go:156:cmd.(ObjectLayer).ListObjects-fm()
       6: cmd/bucket-handlers-listobjects.go:163:cmd.objectAPIHandlers.ListObjectsV1Handler()
       7: cmd/api-router.go:95:cmd.(objectAPIHandlers).ListObjectsV1Handler-fm()
       8: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
```

I have set the policy to `public` for the bucket, but that doesn't help.

## Expected Behavior
Expected behaviour is that the Docker image is uploaded sucessfully

## Current Behavior
Current issue is listing is apparently not possible.

## Your Environment
* Version used (`minio version`): Docker image `minio/minio:RELEASE.2018-05-04T23-13-12Z`
* Environment name and version (e.g. nginx 1.9.1): Docker Registry: `registry:2.5.2`
* Server type and version: Rancher OS version 1.3.0

**Comment by harshavardhana** [comment]
> error parsing HTTP 403 response body: unexpected end of JSON input: ""

The error on the minio console has nothing to do with this error do you have your registry config which you can share , we will try to reproduce this locally ..

**Comment by krishnasrinivas** [comment]
fixed by https://github.com/minio/minio/pull/5900

**Comment by cmdrrobin** [comment]
@harshavardhana sure!

```
#
# Ansible managed
#
version: 0.1
log:
  formatter: text
  fields:
    service: registry
storage:
  cache:
    layerinfo: inmemory
  s3:
    accesskey: <<REMOVED ACCESSKEY>>
    secretkey: <<REMOVED SECRETKEY>>
    region: us-east-1
    regionendpoint: http://minio:9000
    bucket: docker-registry
    encrypt: false
    keyid: mykeyid
    secure: true
    v4auth: true
    chunksize: 5242880
    rootdirectory: /
  delete:
    enabled: true
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

```

**Comment by cmdrrobin** [comment]
@krishnasrinivas that fixed only the unwanted messages. The problem is still there. (at least in my case)

**Comment by harshavardhana** [comment]
is this still a problem @rgruyters - would you mind testing with latest release?

**Comment by cmdrrobin** [comment]
@harshavardhana sorry for the delay, but yeah problem still exists:

```
cf7731d897ee: Pushing  4.096kB
e08128842546: Pushing  10.78MB/60.49MB
8cece0d04918: Pushing  11.78kB
5bef08742407: Pushing  4.221MB
error parsing HTTP 403 response body: unexpected end of JSON input: ""
```

**Comment by cmdrrobin** [comment]
@harshavardhana FYI, I use Docker image `minio/minio` with tag `RELEASE.2018-06-09T03-43-35Z`.

**Comment by harshavardhana** [comment]
> secure: true

The problem looks like in the registry config @rgruyters you have set `secure: true`  and your URL seems to be `http://minio:9000`

**Comment by cmdrrobin** [comment]
@harshavardhana changed it unfortunately it didn't help

**Comment by harshavardhana** [comment]
> @harshavardhana changed it unfortunately it didn't help

Here is a working config that I have locally. 

```
$ cat ~/docker-compose/registry/Dockerfile 
FROM registry:2.6
COPY config.yml /etc/docker/registry/config.yml
```

```
$ cat ~/docker-compose/registry/config.yml 
version: 0.1
log:
    fields:
        service: registry
http:
    addr: :5000
storage:
    cache:
        layerinfo: inmemory
    s3:
        accesskey: minio
        secretkey: minio123
        region: us-east-1
        regionendpoint: http://172.17.0.1:9000
        bucket: docker-registry
        encrypt: false
        secure: false
        v4auth: true
        chunksize: 5242880
        rootdirectory: /
```

**Comment by kannappanr** [comment]
@rgruyters Can you please update the status on this issue? Did the config provided in the previous comment help?

**Comment by cmdrrobin** [comment]
@kannappanr sorry for the delay, but no it didn't solve my problem. I have used @harshavardhana example config but still same issue.

**Comment by harshavardhana** [comment]
> @kannappanr sorry for the delay, but no it didn't solve my problem. I have used @harshavardhana example config but still same issue.

Can you validate again with latest Minio release?

**Comment by harshavardhana** [comment]
> Can you validate again with latest Minio release?

Were you able to validate this again @rgruyters? - we cannot seem to reproduce this problem.

**Comment by harshavardhana** [comment]
Closing this as a stale issue.. feel free to re-open if it can be reproduced with latest release.

**Comment by rgruyters** [comment]
Sorry guys for not keeping up to date, unfortunately problem is still here.

I now have used registry version 2.6 and minio "latest" Docker images. When deploying Minio I only have `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY` set.

and the following Docker registry config:

```
version: 0.1
log:
    fields:
        service: registry
http:
    addr: :5000
    tls:
      certificate: /etc/docker/registry/certs/server.crt
      key: /etc/docker/registry/certs/server.key
storage:
    cache:
        layerinfo: inmemory
    s3:
        accesskey: <<removed>>
        secretkey: <<removed>>
        region: us-east-1
        regionendpoint: http://minio:9000
        bucket: docker-registry
        encrypt: false
        secure: false
        v4auth: true
        chunksize: 5242880
        rootdirectory: /
```

Then I have created the bucket in Minio and try to upload again, but still the same problem:
```
cd7100a72410: Pushing [==================================================>]  4.403MB
error parsing HTTP 403 response body: unexpected end of JSON input: ""
```

The policy is set to "public"
```
$ ./mc policy public local/docker-registry
Access permission for `local/docker-registry` is set to `public`
```
