### ISSUE TITLE
Unexpected errors

### ISSUE THREAD

**Issue by stokowski** [minio/minio#7588]
```
API: SYSTEM()
Time: 12:44:55 UTC 04/26/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/bitrot-streaming.go:45:cmd.(*streamingBitrotWriter).Write()
       2: cmd/erasure-encode.go:48:cmd.(*parallelWriter).Write.func1()

API: SYSTEM()
Time: 12:44:55 UTC 04/26/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/bitrot-streaming.go:45:cmd.(*streamingBitrotWriter).Write()
       2: cmd/erasure-encode.go:48:cmd.(*parallelWriter).Write.func1()

API: SYSTEM()
Time: 12:44:55 UTC 04/26/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/bitrot-streaming.go:45:cmd.(*streamingBitrotWriter).Write()
       2: cmd/erasure-encode.go:48:cmd.(*parallelWriter).Write.func1()

API: SYSTEM()
Time: 12:44:55 UTC 04/26/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/bitrot-streaming.go:45:cmd.(*streamingBitrotWriter).Write()
       2: cmd/erasure-encode.go:48:cmd.(*parallelWriter).Write.func1()

API: SYSTEM()
Time: 12:44:55 UTC 04/26/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/bitrot-streaming.go:45:cmd.(*streamingBitrotWriter).Write()
       2: cmd/erasure-encode.go:48:cmd.(*parallelWriter).Write.func1()

API: SYSTEM()
Time: 12:44:55 UTC 04/26/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/bitrot-streaming.go:45:cmd.(*streamingBitrotWriter).Write()
       2: cmd/erasure-encode.go:48:cmd.(*parallelWriter).Write.func1()

API: PutObject(bucket=somebucket, object=hls/delivery/ch3/ve/gen1_300415_500k/gen1_300415_500k_00000000.ts)
Time: 12:44:55 UTC 04/26/2019
RequestID: 1599065B563F6E1C
RemoteHost: **xxx.xxx.xxx.xxx**
UserAgent: rclone/v1.46
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()
       2: cmd/xl-v1-object.go:679:cmd.xlObjects.putObject()
       3: cmd/xl-v1-object.go:537:cmd.xlObjects.PutObject()
       4: cmd/xl-sets.go:608:cmd.(*xlSets).PutObject()
       5: cmd/object-handlers.go:1254:cmd.objectAPIHandlers.PutObjectHandler()
       6: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()

API: PutObject(bucket=somebucket, object=hls/delivery/ch3/ve/gen1_300415_500k/gen1_300415_500k_00000000.ts)
Time: 12:44:55 UTC 04/26/2019
RequestID: 1599065B563F6E1C
RemoteHost: **xxx.xxx.xxx.xxx**
UserAgent: rclone/v1.46
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/api-errors.go:1660:cmd.toAPIErrorCode()
       2: cmd/api-errors.go:1685:cmd.toAPIError()
       3: cmd/object-handlers.go:1256:cmd.objectAPIHandlers.PutObjectHandler()
       4: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 12:44:56 UTC 04/26/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/bitrot-streaming.go:45:cmd.(*streamingBitrotWriter).Write()
       2: cmd/erasure-encode.go:48:cmd.(*parallelWriter).Write.func1()

API: SYSTEM()
Time: 12:44:56 UTC 04/26/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/bitrot-streaming.go:45:cmd.(*streamingBitrotWriter).Write()
       2: cmd/erasure-encode.go:48:cmd.(*parallelWriter).Write.func1()

API: SYSTEM()
Time: 12:44:56 UTC 04/26/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/bitrot-streaming.go:45:cmd.(*streamingBitrotWriter).Write()
       2: cmd/erasure-encode.go:48:cmd.(*parallelWriter).Write.func1()

API: SYSTEM()
Time: 12:44:56 UTC 04/26/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/bitrot-streaming.go:45:cmd.(*streamingBitrotWriter).Write()
       2: cmd/erasure-encode.go:48:cmd.(*parallelWriter).Write.func1()

API: SYSTEM()
Time: 12:44:56 UTC 04/26/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/bitrot-streaming.go:45:cmd.(*streamingBitrotWriter).Write()
       2: cmd/erasure-encode.go:48:cmd.(*parallelWriter).Write.func1()

API: SYSTEM()
Time: 12:44:56 UTC 04/26/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/bitrot-streaming.go:45:cmd.(*streamingBitrotWriter).Write()
       2: cmd/erasure-encode.go:48:cmd.(*parallelWriter).Write.func1()

API: PutObject(bucket=somebucket, object=hls/delivery/ch3/ve/gen2_010216_500k/gen2_010216_500k_00000000.ts)
Time: 12:44:56 UTC 04/26/2019
RequestID: 1599068549A87DB4
RemoteHost: **xxx.xxx.xxx.xxx**
UserAgent: rclone/v1.46
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()
       2: cmd/xl-v1-object.go:679:cmd.xlObjects.putObject()
       3: cmd/xl-v1-object.go:537:cmd.xlObjects.PutObject()
       4: cmd/xl-sets.go:608:cmd.(*xlSets).PutObject()
       5: cmd/object-handlers.go:1254:cmd.objectAPIHandlers.PutObjectHandler()
       6: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()

API: PutObject(bucket=somebucket, object=hls/delivery/ch3/ve/gen2_010216_500k/gen2_010216_500k_00000000.ts)
Time: 12:44:56 UTC 04/26/2019
RequestID: 1599068549A87DB4
RemoteHost: **xxx.xxx.xxx.xxx**
UserAgent: rclone/v1.46
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/api-errors.go:1660:cmd.toAPIErrorCode()
       2: cmd/api-errors.go:1685:cmd.toAPIError()
       3: cmd/object-handlers.go:1256:cmd.objectAPIHandlers.PutObjectHandler()
       4: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 12:44:58 UTC 04/26/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/bitrot-streaming.go:45:cmd.(*streamingBitrotWriter).Write()
       2: cmd/erasure-encode.go:48:cmd.(*parallelWriter).Write.func1()

API: SYSTEM()
Time: 12:44:58 UTC 04/26/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/bitrot-streaming.go:45:cmd.(*streamingBitrotWriter).Write()
       2: cmd/erasure-encode.go:48:cmd.(*parallelWriter).Write.func1()

API: SYSTEM()
Time: 12:44:58 UTC 04/26/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/bitrot-streaming.go:45:cmd.(*streamingBitrotWriter).Write()
       2: cmd/erasure-encode.go:48:cmd.(*parallelWriter).Write.func1()

API: SYSTEM()
Time: 12:44:58 UTC 04/26/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/bitrot-streaming.go:45:cmd.(*streamingBitrotWriter).Write()
       2: cmd/erasure-encode.go:48:cmd.(*parallelWriter).Write.func1()

API: SYSTEM()
Time: 12:44:58 UTC 04/26/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/bitrot-streaming.go:45:cmd.(*streamingBitrotWriter).Write()
       2: cmd/erasure-encode.go:48:cmd.(*parallelWriter).Write.func1()

API: SYSTEM()
Time: 12:44:58 UTC 04/26/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/bitrot-streaming.go:45:cmd.(*streamingBitrotWriter).Write()
       2: cmd/erasure-encode.go:48:cmd.(*parallelWriter).Write.func1()

API: PutObject(bucket=somebucket, object=hls/delivery/ch3/ve/gen2_010615_500k/gen2_010615_500k_00000000.ts)
Time: 12:44:58 UTC 04/26/2019
RequestID: 15990695DAE47B57
RemoteHost: **xxx.xxx.xxx.xxx**
UserAgent: rclone/v1.46
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()
       2: cmd/xl-v1-object.go:679:cmd.xlObjects.putObject()
       3: cmd/xl-v1-object.go:537:cmd.xlObjects.PutObject()
       4: cmd/xl-sets.go:608:cmd.(*xlSets).PutObject()
       5: cmd/object-handlers.go:1254:cmd.objectAPIHandlers.PutObjectHandler()
       6: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()

API: PutObject(bucket=somebucket, object=hls/delivery/ch3/ve/gen2_010615_500k/gen2_010615_500k_00000000.ts)
Time: 12:44:58 UTC 04/26/2019
RequestID: 15990695DAE47B57
RemoteHost: **xxx.xxx.xxx.xxx**
UserAgent: rclone/v1.46
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/api-errors.go:1660:cmd.toAPIErrorCode()
       2: cmd/api-errors.go:1685:cmd.toAPIError()
       3: cmd/object-handlers.go:1256:cmd.objectAPIHandlers.PutObjectHandler()
       4: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()


```

Im synchronizing two buckets separately of the same minio instance with some other storage - couple million of objects on both buckets with object size xxx KB to xxx MB. 

Current operations are: 1st bucket - mainly object checks/compares based on size (--size-only flag in rclone); 2nd bucket - up to 20 concurrent upload of files xx-xxx MB.

In meantime rclone also catched such errors for few moments:

```
2019-04-26 12:35:30 ERROR : hls/delivery/ch3/ve/gen1_300115_1000k/gen1_300115_1000k_00000000.ts: Failed to copy: MultipartUpload: upload multipart failed
        upload id: 70a04216-3178-457a-9f54-90e507be2ccb
caused by: InvalidAccessKeyId: The access key ID you provided does not exist in our records.
        status code: 403, request id: , host id:
2019-04-26 12:35:30 ERROR : hls/delivery/ch3/ve/gen1_300315_1000k/gen1_300315_1000k_00000000.ts: Failed to copy: MultipartUpload: upload multipart failed
        upload id: f9f58c5a-4a36-4f50-89e8-b3cde38ced16
caused by: InvalidAccessKeyId: The access key ID you provided does not exist in our records.
        status code: 403, request id: , host id:
2019-04-26 12:35:31 ERROR : hls/delivery/ch3/ve/gen1_300115_2200k/gen1_300115_2200k_00000000.ts: Failed to copy: MultipartUpload: upload multipart failed
        upload id: 111df434-1b3a-4d90-a2fd-7cfd84e7edea
caused by: InvalidAccessKeyId: The access key ID you provided does not exist in our records.
```

this could be related to bandwidthlimit that i've set for file uploads.

Also on one node, minio process have created about ~430 threads and that number is growing. For now i'm not killing that process, want to see what will happen.

Maybe there is somekind of deadlock inside ?

## Your Environment
* Version used (`minio version`):

RELEASE.2019-04-23T23-50-36Z

* Environment name and version (e.g. nginx 1.9.1):

Docker / Kubernetes / Proxy on front
3 nodes / 6 disks

Rclone 1.46

**Comment by nitisht** [comment]
Thanks for reporting, we'll take a look @stokowski

**Comment by stokowski** [comment]
Hi,

Syncing continues. The number of minio process threads have grown to ~1900. Looks like old threads are not closed. That threads-case is only on one node from 3 (distributed mode). No network/disks bottlenecks. If needed I can attach strace log.

**Comment by harshavardhana** [comment]
Most probably fixed by #7590

**Comment by harshavardhana** [comment]
@stokowski can you test with latest master?

**Comment by stokowski** [comment]
@harshavardhana im testing latest edge docker image. I will let you know if problem still occurs.

**Comment by harshavardhana** [comment]
> @harshavardhana im testing latest edge docker image. I will let you know if problem still occurs.

Thanks @stokowski

**Comment by stokowski** [comment]
Hi,

I dont see issues with drastically increasing number of minio threads. But when doing many syncs I've catched some errors on uploads:

```
Time: 09:02:38 UTC 04/30/2019
RequestID: 159A350EB16544CE
RemoteHost: yyy.yyy.yyy.yyy
UserAgent: rclone/v1.46
Error: Write failed. Insufficient number of disks online
       1: /go/minio/cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()
       2: /go/minio/cmd/xl-v1-object.go:682:cmd.xlObjects.putObject()
       3: /go/minio/cmd/xl-v1-object.go:540:cmd.xlObjects.PutObject()
       4: /go/minio/cmd/xl-sets.go:608:cmd.(*xlSets).PutObject()
       5: /go/minio/cmd/object-handlers.go:1254:cmd.objectAPIHandlers.PutObjectHandler()
       6: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()
API: SYSTEM()
Time: 09:02:38 UTC 04/30/2019
Error: open /data/store03/instance/.minio.sys/tmp/b7bbb284-948b-44a4-8d90-64cec4fff34a/part.1: invalid argument
       storageDisk=https://xxx.xxx.xxx.xxx/data/store03/instance
       1: /go/minio/cmd/bitrot-streaming.go:89:cmd.newStreamingBitrotWriter.func1()
API: SYSTEM()
Time: 09:02:38 UTC 04/30/2019
Error: open /data/store04/instance/.minio.sys/tmp/b7bbb284-948b-44a4-8d90-64cec4fff34a/part.1: invalid argument
       storageDisk=https://xxx.xxx.xxx.xxx:9001/data/store04/instance
       1: /go/minio/cmd/bitrot-streaming.go:89:cmd.newStreamingBitrotWriter.func1()
API: SYSTEM()
Time: 09:02:46 UTC 04/30/2019
Error: open /data/store04/instance/.minio.sys/tmp/a3678377-4681-49ee-b3d9-cb4c8754ac2b/part.1: invalid argument
       storageDisk=/data/store04/instance
       1: /go/minio/cmd/bitrot-streaming.go:89:cmd.newStreamingBitrotWriter.func1()
API: SYSTEM()
Time: 09:02:46 UTC 04/30/2019
Error: open /data/store03/instance/.minio.sys/tmp/a3678377-4681-49ee-b3d9-cb4c8754ac2b/part.1: invalid argument
       storageDisk=/data/store03/instance
       1: /go/minio/cmd/bitrot-streaming.go:89:cmd.newStreamingBitrotWriter.func1() 
```

which is strange because I dont have problems with disks, also minio admin info also reported no issues. Im trying to reproduce that.

**Comment by stokowski** [comment]
Problem repeated for me on different instance, with the same edge version from yesterday.

**Comment by harshavardhana** [comment]
This looks like your disk is giving up on load, low level calls cannot return "invalid argument"

What is the disk here ? A k8s storage volume?

**Comment by harshavardhana** [comment]
This is different than the original issue, can we close this and reopen a new one?

**Comment by stokowski** [comment]
Nah, host volume. Yeah go ahead and close it.

**Comment by kannappanr** [comment]
@stokowski Closing this issue now. Please feel free to open another issue if you have further questions.
