### ISSUE TITLE
Error uploading large files to MinIO server

### ISSUE THREAD

**Issue by danilonet** [minio/minio#8124]
## Expected Behavior
upload successful

## Current Behavior
MinIO API responded with message=The request signature we calculated does not match the signature you provided. Check your key and signing method.

## Steps to Reproduce (for bugs)
c# client, verson 3.0.12
latest docker server
this is my code:

public async Task UploadFile(string bucketName, Stream fileStream, string fileName, long fileSize, string contentType)
{
            bool found = await minioClient.BucketExistsAsync(bucketName);
            if (!found)
            {
                await minioClient.MakeBucketAsync(bucketName);
            }
            // Upload a file to bucket.
            await minioClient.PutObjectAsync(bucketName, fileName, fileStream, fileSize, contentType);
}
where:
bucketName : "patients"
stream : the resulting stream from an upload to a asp.net web page
fileSize: 19589050
content-type: "application/pdf"

it works fine with smallest PDF files (40KB, 100KB) but if i try to upload biggest files (20 MB for example) i have this exception:

MinIO API responded with message=The request signature we calculated does not match the signature you provided. Check your key and signing method.

STACKTRACE:

in Minio.MinioClient.ParseError(IRestResponse response) in Minio.MinioClient.<>c.<.ctor>b__80_0(IRestResponse response) in Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in Minio.MinioClient.d__84.MoveNext() --- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione --- in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in Minio.MinioClient.d__20.MoveNext() --- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione --- in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) in Minio.MinioClient.d__15.MoveNext() --- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione --- in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in System.Runtime.CompilerServices.TaskAwaiter.GetResult() in API.Managers.MinIOManager.d__5.MoveNext() in C:\Users\dcalzetta\source\repos\TPO_Web\API\Managers\MinIOManager.cs:riga 43 --- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione --- in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in System.Runtime.CompilerServices.TaskAwaiter.GetResult() in API.Controllers.DocumentController.d__7.MoveNext() in C:\Users\dcalzetta\source\repos\TPO_Web\API\Controllers\DocumentController.cs:riga 288

**where i'm wrong?**

i'm using a docker MINIO server for develompent scope,
minio/minio       latest   77a8467ccda1        8 days ago     63.5MB

docker run -d -p 9000:9000 -v /opt/minio/data:/data --restart unless-stopped -e "MINIO_ACCESS_KEY=xxxxxxx" -e "MINIO_SECRET_KEY=yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy" minio/minio server /data

in my web.config i extended max upload size to 100Mb,

  <system.web>
    <compilation debug="true" targetFramework="4.6.2" />
    <httpRuntime targetFramework="4.6.1" maxRequestLength="102428" />
  </system.web>

...

  <system.webServer>
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="102428800" />
      </requestFiltering>
    </security>

**Comment by nitisht** [comment]
Thanks for reporting @danilonet we'll take a look

**Comment by eco-minio** [comment]
@danilonet Were you able to test with latest dotnet version?  If it is still an issue please provide the trace output requested.

**Comment by danilonet** [comment]
hello,
i tested the upload with a fresh new C# project and it works fine,
then the MiniIO client library don't works on the enviroment in my project in visual studio .

CLIENT LOG FAILURE CASE:
--------------------------------
The thread 0x24bc has exited with code 0 (0x0).
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'Minio.Exceptions.MinioException' in Minio.dll
Exception thrown: 'Minio.Exceptions.MinioException' in mscorlib.dll
Exception thrown: 'Minio.Exceptions.MinioException' in mscorlib.dll
Exception thrown: 'Minio.Exceptions.MinioException' in mscorlib.dll
Exception thrown: 'Minio.Exceptions.MinioException' in mscorlib.dll
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.RemoteDependency","time":"2019-09-05T14:47:27.9411212Z","tags":{"ai.cloud.roleInstance":"sstpdcalzetta.athena.local","ai.operation.id":"84058c3e-447877ab139850ea","ai.operation.name":"POST Document/SaveUploadFile","ai.location.ip":"::1","ai.internal.sdkVersion":"rdddsd:2.5.1-195","ai.internal.nodeName":"sstpdcalzetta.athena.local"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"POST /api/document/UploadDocumentFile","id":"|84058c3e-447877ab139850ea.","data":"http://localhost:56000/api/document/UploadDocumentFile","duration":"00:00:08.1905591","resultCode":"200","success":true,"type":"Http","target":"localhost:56000","properties":{"DeveloperMode":"true","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.0')"}}}}
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.RemoteDependency","time":"2019-09-05T14:47:36.1655272Z","tags":{"ai.cloud.roleInstance":"sstpdcalzetta.athena.local","ai.operation.id":"84058c3f-447877ab139850ea","ai.operation.name":"POST Document/SaveUploadFile","ai.location.ip":"::1","ai.internal.sdkVersion":"rdddsd:2.5.1-195","ai.internal.nodeName":"sstpdcalzetta.athena.local"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"POST /api/document/DeleteDocumentFileById","id":"|84058c3f-447877ab139850ea.","data":"http://localhost:56000/api/document/DeleteDocumentFileById?id=112","duration":"00:00:00.0710744","resultCode":"200","success":true,"type":"Http","target":"localhost:56000","properties":{"DeveloperMode":"true","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.0')"}}}}
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Request","time":"2019-09-05T14:47:27.2661337Z","tags":{"ai.cloud.roleInstance":"sstpdcalzetta.athena.local","ai.operation.id":"2q11i0jI5wk=","ai.operation.name":"POST Document/SaveUploadFile","ai.location.ip":"::1","ai.internal.sdkVersion":"web:2.5.1-195","ai.internal.nodeName":"sstpdcalzetta.athena.local"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"|2q11i0jI5wk=.84058c3c_","name":"POST Document/SaveUploadFile","duration":"00:00:09.0019313","success":false,"responseCode":"400","url":"http://localhost:56001/Document/SaveUploadFile?FolderId=3&PatientId=1","properties":{"DeveloperMode":"true","_MS.ProcessedByMetricExtractors":"(Name:'Requests', Ver:'1.0')"}}}}
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.RemoteDependency","time":"2019-09-05T14:47:36.3015253Z","tags":{"ai.cloud.roleInstance":"sstpdcalzetta.athena.local","ai.operation.id":"84058c41-447877ab139850ea","ai.operation.name":"POST APIDataTable/ApiListDocumentsByFilter","ai.location.ip":"::1","ai.internal.sdkVersion":"rdddsd:2.5.1-195","ai.internal.nodeName":"sstpdcalzetta.athena.local"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"POST /api/document/GetDocumentsByFilter","id":"|84058c41-447877ab139850ea.","data":"http://localhost:56000/api/document/GetDocumentsByFilter","duration":"00:00:00.1289509","resultCode":"200","success":true,"type":"Http","target":"localhost:56000","properties":{"DeveloperMode":"true","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.0')"}}}}
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Request","time":"2019-09-05T14:47:36.2965291Z","tags":{"ai.cloud.roleInstance":"sstpdcalzetta.athena.local","ai.operation.id":"AlQXV2jNeHI=","ai.operation.name":"POST APIDataTable/ApiListDocumentsByFilter","ai.location.ip":"::1","ai.internal.sdkVersion":"web:2.5.1-195","ai.internal.nodeName":"sstpdcalzetta.athena.local"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"|AlQXV2jNeHI=.84058c40_","name":"POST APIDataTable/ApiListDocumentsByFilter","duration":"00:00:00.1636652","success":true,"responseCode":"200","url":"http://localhost:56001/APIDataTable/ApiListDocumentsByFilter","properties":{"DeveloperMode":"true","_MS.ProcessedByMetricExtractors":"(Name:'Requests', Ver:'1.0')"}}}}


CLIENT LOG SUCCESS CASE
-------------------------------
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.RemoteDependency","time":"2019-09-05T14:48:27.6257217Z","tags":{"ai.cloud.roleInstance":"sstpdcalzetta.athena.local","ai.operation.id":"84058c46-447877ab139850ea","ai.operation.name":"POST Document/SaveUploadFile","ai.location.ip":"::1","ai.internal.sdkVersion":"rdddsd:2.5.1-195","ai.internal.nodeName":"sstpdcalzetta.athena.local"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"POST /api/document/UploadDocumentFile","id":"|84058c46-447877ab139850ea.","data":"http://localhost:56000/api/document/UploadDocumentFile","duration":"00:00:00.0801262","resultCode":"200","success":true,"type":"Http","target":"localhost:56000","properties":{"DeveloperMode":"true","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.0')"}}}}
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Request","time":"2019-09-05T14:48:27.5193407Z","tags":{"ai.cloud.roleInstance":"sstpdcalzetta.athena.local","ai.operation.id":"lafInFGDgXQ=","ai.operation.name":"POST Document/SaveUploadFile","ai.location.ip":"::1","ai.internal.sdkVersion":"web:2.5.1-195","ai.internal.nodeName":"sstpdcalzetta.athena.local"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"|lafInFGDgXQ=.84058c44_","name":"POST Document/SaveUploadFile","duration":"00:00:00.2126552","success":true,"responseCode":"200","url":"http://localhost:56001/Document/SaveUploadFile?FolderId=3&PatientId=1","properties":{"DeveloperMode":"true","_MS.ProcessedByMetricExtractors":"(Name:'Requests', Ver:'1.0')"}}}}
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.RemoteDependency","time":"2019-09-05T14:48:27.7987201Z","tags":{"ai.cloud.roleInstance":"sstpdcalzetta.athena.local","ai.operation.id":"84058c48-447877ab139850ea","ai.operation.name":"POST APIDataTable/ApiListDocumentsByFilter","ai.location.ip":"::1","ai.internal.sdkVersion":"rdddsd:2.5.1-195","ai.internal.nodeName":"sstpdcalzetta.athena.local"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"POST /api/document/GetDocumentsByFilter","id":"|84058c48-447877ab139850ea.","data":"http://localhost:56000/api/document/GetDocumentsByFilter","duration":"00:00:00.1051754","resultCode":"200","success":true,"type":"Http","target":"localhost:56000","properties":{"DeveloperMode":"true","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.0')"}}}}
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Request","time":"2019-09-05T14:48:27.7797181Z","tags":{"ai.cloud.roleInstance":"sstpdcalzetta.athena.local","ai.operation.id":"+1VrzD167nc=","ai.operation.name":"POST APIDataTable/ApiListDocumentsByFilter","ai.location.ip":"::1","ai.internal.sdkVersion":"web:2.5.1-195","ai.internal.nodeName":"sstpdcalzetta.athena.local"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"|+1VrzD167nc=.84058c47_","name":"POST APIDataTable/ApiListDocumentsByFilter","duration":"00:00:00.1560919","success":true,"responseCode":"200","url":"http://localhost:56001/APIDataTable/ApiListDocumentsByFilter","properties":{"DeveloperMode":"true","_MS.ProcessedByMetricExtractors":"(Name:'Requests', Ver:'1.0')"}}}}

**Comment by danilonet** [comment]
also this is my web config
-----------------------

```
<?xml version="1.0" encoding="utf-8"?>
<!--
  For more information on how to configure your ASP.NET application, please visit
  https://go.microsoft.com/fwlink/?LinkId=301880
  -->
<configuration>
  <configSections>

    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
    <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 -->
  </configSections>
  <appSettings>
    
  </appSettings>
  <system.web>
    <authentication mode="None" />
    <compilation debug="true" targetFramework="4.6.2" />
    <httpRuntime targetFramework="4.6.2" maxRequestLength="52428" />
    <httpModules>
      <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" />
    </httpModules>
    <customErrors mode="RemoteOnly" defaultRedirect="~/Error" />
  </system.web>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Antlr3.Runtime" publicKeyToken="eb42632606e9261f" />
        <bindingRedirect oldVersion="0.0.0.0-3.5.0.2" newVersion="3.5.0.2" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.1" newVersion="4.0.2.1" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
        <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Optimization" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-1.1.0.0" newVersion="1.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="WebGrease" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-1.6.5135.21930" newVersion="1.6.5135.21930" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.2" newVersion="4.1.1.2" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin.Security.OAuth" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin.Security" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin.Security.Cookies" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Logging" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.4.0.0" newVersion="5.4.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Helpers" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.WebPages" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.7.0" newVersion="5.2.7.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="RestSharp" publicKeyToken="598062e77f915f75" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-106.6.9.0" newVersion="106.6.9.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <system.webServer>
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="52428800" />
      </requestFiltering>
    </security>
    <modules>
      <remove name="TelemetryCorrelationHttpModule" />
      <add name="TelemetryCorrelationHttpModule" type="Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule, Microsoft.AspNet.TelemetryCorrelation" preCondition="integratedMode,managedHandler" />
      <remove name="ApplicationInsightsWebTracking" />
      <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" preCondition="managedHandler" />
      <remove name="FormsAuthenticationModule" />
    </modules>
    <validation validateIntegratedModeConfiguration="false" />
  </system.webServer>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="v13.0" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
    </providers>
  </entityFramework>
  <system.codedom>
    <compilers>
      <compiler language="c#;cs;csharp" extension=".cs" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=2.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:default /nowarn:1659;1699;1701" />
      <compiler language="vb;vbs;visualbasic;vbscript" extension=".vb" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=2.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:default /nowarn:41008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+" />
    </compilers>
  </system.codedom>
</configuration>
```

**Comment by eco-minio** [comment]
These are separate issues, there was a new release yesterday (3.1.4) that should fix the issue you mentioned yesterday.  For the issue regarding large file uploads, please test with the latest.  If this does not work after the upgrade, please attach trace output from `mc admin trace -a -v <alias>`.

**Comment by danilonet** [comment]
hello, i just upgraded minio client to 3.1.4, it runs correctly, 
I also upgraded the server to the latest version
but the large file upload problem still exists.

server trace in error case
----------------

```
172.25.122.135 [REQUEST s3.GetBucketLocation] 22:55:43.706
172.25.122.135 GET /patients?location
172.25.122.135 Host: 172.25.122.135:9000
172.25.122.135 Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
172.25.122.135 Accept-Encoding: gzip, deflate
172.25.122.135 Authorization: AWS4-HMAC-SHA256 Credential=EPN9OZC3LEG232WC072S/20190906/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=52f616a989450fc4d2cf7d544cc829b88a3e7548c0e2b1fea2c5330b270821c1
172.25.122.135 User-Agent: MinIO (Microsoft Windows NT 10.0.17134.0;x86_64) minio-dotnet/1.0.9
172.25.122.135 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
172.25.122.135 X-Amz-Date: 20190906T225543Z
172.25.122.135 Connection: Keep-Alive
172.25.122.135 Content-Length: 0
172.25.122.135
172.25.122.135 [RESPONSE] [22:55:43.706] [ Duration 285µs  🠉 111 B  🠋 378 B ]
172.25.122.135 200 OK
172.25.122.135 Server: MinIO/RELEASE.2019-09-05T23-24-38Z
172.25.122.135 Vary: Origin
172.25.122.135 X-Amz-Request-Id: 15C1FB6204B32CE2
172.25.122.135 X-Xss-Protection: 1; mode=block
172.25.122.135 Accept-Ranges: bytes
172.25.122.135 Content-Length: 128
172.25.122.135 Content-Security-Policy: block-all-mixed-content
172.25.122.135 Content-Type: application/xml
172.25.122.135 <?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>
172.25.122.135
172.25.122.135 [REQUEST s3.HeadBucket] 22:55:43.744
172.25.122.135 HEAD /patients/
172.25.122.135 Host: 172.25.122.135:9000
172.25.122.135 Authorization: AWS4-HMAC-SHA256 Credential=EPN9OZC3LEG232WC072S/20190906/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=45d49a4975dc53f995501acf965524ee5e9581d27b3fea0ea887a2ddb7d39234
172.25.122.135 Content-Length: 0
172.25.122.135 User-Agent: MinIO (Microsoft Windows NT 10.0.17134.0;x86_64) minio-dotnet/1.0.9
172.25.122.135 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
172.25.122.135 X-Amz-Date: 20190906T225543Z
172.25.122.135 Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
172.25.122.135 Accept-Encoding: gzip, deflate
172.25.122.135
172.25.122.135 [RESPONSE] [22:55:43.744] [ Duration 390µs  🠉 100 B  🠋 218 B ]
172.25.122.135 200 OK
172.25.122.135 Accept-Ranges: bytes
172.25.122.135 Content-Length: 0
172.25.122.135 Content-Security-Policy: block-all-mixed-content
172.25.122.135 Server: MinIO/RELEASE.2019-09-05T23-24-38Z
172.25.122.135 Vary: Origin
172.25.122.135 X-Amz-Request-Id: 15C1FB6206FB24A0
172.25.122.135 X-Xss-Protection: 1; mode=block
172.25.122.135
172.25.122.135
172.25.122.135 [REQUEST s3.NewMultipartUpload] 22:55:44.145
172.25.122.135 POST /patients/e8d26655f78d4173b08384c49442d20f.dat?uploads
172.25.122.135 Host: 172.25.122.135:9000
172.25.122.135 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
172.25.122.135 Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
172.25.122.135 Accept-Encoding: gzip, deflate
172.25.122.135 Authorization: AWS4-HMAC-SHA256 Credential=EPN9OZC3LEG232WC072S/20190906/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=cc4a20cd4949e6cd2930e0a2ee420a6e69a39c6533f6b9237992d9a259b522dd
172.25.122.135 Content-Length: 0
172.25.122.135 User-Agent: MinIO (Microsoft Windows NT 10.0.17134.0;x86_64) minio-dotnet/1.0.9
172.25.122.135 Content-Type: application/pdf
172.25.122.135 X-Amz-Date: 20190906T225544Z
172.25.122.135
172.25.122.135 [RESPONSE] [22:55:44.146] [ Duration 538µs  🠉 113 B  🠋 529 B ]
172.25.122.135 200 OK
172.25.122.135 Accept-Ranges: bytes
172.25.122.135 Content-Length: 279
172.25.122.135 Content-Security-Policy: block-all-mixed-content
172.25.122.135 Content-Type: application/xml
172.25.122.135 Server: MinIO/RELEASE.2019-09-05T23-24-38Z
172.25.122.135 Vary: Origin
172.25.122.135 X-Amz-Request-Id: 15C1FB621EE90502
172.25.122.135 X-Xss-Protection: 1; mode=block
172.25.122.135 <?xml version="1.0" encoding="UTF-8"?>
<InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>patients</Bucket><Key>e8d26655f78d4173b08384c49442d20f.dat</Key><UploadId>787118ef-e0a1-4dff-a7ec-a417a3c0f3ba</UploadId></InitiateMultipartUploadResult>
172.25.122.135
172.25.122.135 [REQUEST s3.PutObjectPart] 22:55:44.558
172.25.122.135 PUT /patients/e8d26655f78d4173b08384c49442d20f.dat?uploadId=787118ef-e0a1-4dff-a7ec-a417a3c0f3ba&partNumber=1
172.25.122.135 Host: 172.25.122.135:9000
172.25.122.135 Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
172.25.122.135 Accept-Encoding: gzip, deflate
172.25.122.135 Content-Type: application/pdf
172.25.122.135 User-Agent: MinIO (Microsoft Windows NT 10.0.17134.0;x86_64) minio-dotnet/1.0.9
172.25.122.135 X-Amz-Content-Sha256: 7e32c459a50e61d03afb4f3b3b580bacd677875430ab14255b723b60414e6b26
172.25.122.135 Authorization: AWS4-HMAC-SHA256 Credential=EPN9OZC3LEG232WC072S/20190906/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=b3be5896812246b114b149cb1dee3bc9dca0a6b5601a8826f15016890ac546f7
172.25.122.135 Content-Length: 5242880
172.25.122.135 X-Amz-Date: 20190906T225544Z
172.25.122.135 <BODY>
172.25.122.135 [RESPONSE] [22:55:44.569] [ Duration 11.61ms  🠉 113 B  🠋 716 B ]
172.25.122.135 403 Forbidden
172.25.122.135 Accept-Ranges: bytes
172.25.122.135 Content-Length: 459
172.25.122.135 Content-Security-Policy: block-all-mixed-content
172.25.122.135 Content-Type: application/xml
172.25.122.135 Server: MinIO/RELEASE.2019-09-05T23-24-38Z
172.25.122.135 Vary: Origin
172.25.122.135 X-Amz-Request-Id: 15C1FB6237808925
172.25.122.135 X-Xss-Protection: 1; mode=block
172.25.122.135 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>e8d26655f78d4173b08384c49442d20f.dat</Key><BucketName>patients</BucketName><Resource>/patients/e8d26655f78d4173b08384c49442d20f.dat</Resource><RequestId>15C1FB6237808925</RequestId><HostId>468986af-d10d-4f25-93f2-6e3ee55f8d82</HostId></Error>
172.25.122.135
172.25.122.135 [REQUEST s3.DeleteObject] 22:55:44.970
172.25.122.135 DELETE /patients/e8d26655f78d4173b08384c49442d20f.dat
172.25.122.135 Host: 172.25.122.135:9000
172.25.122.135 Accept-Encoding: gzip, deflate
172.25.122.135 Authorization: AWS4-HMAC-SHA256 Credential=EPN9OZC3LEG232WC072S/20190906/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=0d492d245b6508731f6e457f0cbdb739f0ab736885dfc094aa61799abe570939
172.25.122.135 Content-Length: 0
172.25.122.135 User-Agent: MinIO (Microsoft Windows NT 10.0.17134.0;x86_64) minio-dotnet/1.0.9
172.25.122.135 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
172.25.122.135 X-Amz-Date: 20190906T225545Z
172.25.122.135 Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
172.25.122.135
172.25.122.135 [RESPONSE] [22:55:44.970] [ Duration 249µs  🠉 100 B  🠋 226 B ]
172.25.122.135 204 No Content
172.25.122.135 X-Amz-Request-Id: 15C1FB625011046C
172.25.122.135 X-Xss-Protection: 1; mode=block
172.25.122.135 Accept-Ranges: bytes
172.25.122.135 Content-Length: 0
172.25.122.135 Content-Security-Policy: block-all-mixed-content
172.25.122.135 Server: MinIO/RELEASE.2019-09-05T23-24-38Z
172.25.122.135 Vary: Origin
```


Else uploading a small file <2Mb, it works
-----

```
172.25.122.135 [REQUEST s3.HeadBucket] 22:57:06.598
172.25.122.135 HEAD /patients/
172.25.122.135 Host: 172.25.122.135:9000
172.25.122.135 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
172.25.122.135 X-Amz-Date: 20190906T225706Z
172.25.122.135 Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
172.25.122.135 Accept-Encoding: gzip, deflate
172.25.122.135 Authorization: AWS4-HMAC-SHA256 Credential=EPN9OZC3LEG232WC072S/20190906/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=6158627ae08f7aa443b16fb556baed17ee96ebc23aa790ef24b43c8b32b7a514
172.25.122.135 Content-Length: 0
172.25.122.135 User-Agent: MinIO (Microsoft Windows NT 10.0.17134.0;x86_64) minio-dotnet/1.0.9
172.25.122.135
172.25.122.135 [RESPONSE] [22:57:06.599] [ Duration 165µs  🠉 100 B  🠋 218 B ]
172.25.122.135 200 OK
172.25.122.135 Content-Length: 0
172.25.122.135 Content-Security-Policy: block-all-mixed-content
172.25.122.135 Server: MinIO/RELEASE.2019-09-05T23-24-38Z
172.25.122.135 Vary: Origin
172.25.122.135 X-Amz-Request-Id: 15C1FB75517ECCF5
172.25.122.135 X-Xss-Protection: 1; mode=block
172.25.122.135 Accept-Ranges: bytes
172.25.122.135
172.25.122.135
172.25.122.135 [REQUEST s3.PutObject] 22:57:06.621
172.25.122.135 PUT /patients/7ad03c475ae248c984228abef1203e05.dat
172.25.122.135 Host: 172.25.122.135:9000
172.25.122.135 Content-Type: application/pdf
172.25.122.135 User-Agent: MinIO (Microsoft Windows NT 10.0.17134.0;x86_64) minio-dotnet/1.0.9
172.25.122.135 X-Amz-Content-Sha256: 8decc8571946d4cd70a024949e033a2a2a54377fe9f1c1b944c20f9ee11a9e51
172.25.122.135 X-Amz-Date: 20190906T225706Z
172.25.122.135 Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
172.25.122.135 Accept-Encoding: gzip, deflate
172.25.122.135 Authorization: AWS4-HMAC-SHA256 Credential=EPN9OZC3LEG232WC072S/20190906/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=a38ee11b554288aad2e6b1c2becc362a18a9b1638377f222dd6065f608fba5e3
172.25.122.135 Content-Length: 3028
172.25.122.135 <BODY>
172.25.122.135 [RESPONSE] [22:57:06.624] [ Duration 3.555ms  🠉 3.1 KiB  🠋 261 B ]
172.25.122.135 200 OK
172.25.122.135 ETag: "9354eff6335c6f069525b8a0d31b5646-1"
172.25.122.135 Server: MinIO/RELEASE.2019-09-05T23-24-38Z
172.25.122.135 Vary: Origin
172.25.122.135 X-Amz-Request-Id: 15C1FB7552D2D664
172.25.122.135 X-Xss-Protection: 1; mode=block
172.25.122.135 Accept-Ranges: bytes
172.25.122.135 Content-Length: 0
172.25.122.135 Content-Security-Policy: block-all-mixed-content
172.25.122.135 <BODY>
172.25.122.135
```

**Comment by poornas** [comment]
@danilonet , can you also set `minioClient.SetTraceOn();` - and attach client side of the trace. We need to see if client sent any extra header or different header value - and compare that against what the minio server used for the authorization.

**Comment by danilonet** [comment]
here you can find both, server and client log 

CLIENT LOG
-------------------
```
'iisexpress.exe' (CLR v4.0.30319: /LM/W3SVC/6/ROOT-1-132123679655413330): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Dynamic\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Dynamic.dll'. Cannot find or open the PDB file.
'iisexpress.exe' (CLR v4.0.30319: /LM/W3SVC/6/ROOT-1-132123679655413330): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp.resources\v4.0_4.0.0.0_it_b03f5f7f11d50a3a\Microsoft.CSharp.resources.dll'. Module was built without symbols.
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
'iisexpress.exe' (CLR v4.0.30319: /LM/W3SVC/6/ROOT-1-132123679655413330): Loaded 'Microsoft.GeneratedCode'. 
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
'iisexpress.exe' (CLR v4.0.30319: /LM/W3SVC/6/ROOT-1-132123679655413330): Loaded 'Microsoft.GeneratedCode'. 
Exception thrown: 'Minio.Exceptions.MinioException' in Minio.dll
Exception thrown: 'Minio.Exceptions.MinioException' in mscorlib.dll
Exception thrown: 'Minio.Exceptions.MinioException' in mscorlib.dll
Exception thrown: 'Minio.Exceptions.MinioException' in mscorlib.dll
Exception thrown: 'Minio.Exceptions.MinioException' in mscorlib.dll
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'System.ArgumentException' in mscorlib.dll
```

SERVER LOG
------------------
```
root@zurmotest01:/home/dcalzetta# ./mc admin trace -a -v minio
172.25.122.135 [REQUEST s3.GetBucketLocation] 22:13:54.776
172.25.122.135 GET /patients?location
172.25.122.135 Host: 172.25.122.135:9000
172.25.122.135 Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
172.25.122.135 Authorization: AWS4-HMAC-SHA256 Credential=EPN9OZC3LEG232WC072S/20190907/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=2517e53258ebb5064c16f060e036b66df199dc5d460e1ad1436af458840dfddb
172.25.122.135 X-Amz-Date: 20190907T221355Z
172.25.122.135 Accept-Encoding: gzip, deflate
172.25.122.135 Connection: Keep-Alive
172.25.122.135 Content-Length: 0
172.25.122.135 User-Agent: MinIO (Microsoft Windows NT 10.0.17134.0;x86_64) minio-dotnet/1.0.9
172.25.122.135 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
172.25.122.135
172.25.122.135 [RESPONSE] [22:13:54.776] [ Duration 262µs  🠉 111 B  🠋 378 B ]
172.25.122.135 200 OK
172.25.122.135 Content-Type: application/xml
172.25.122.135 Server: MinIO/RELEASE.2019-09-05T23-24-38Z
172.25.122.135 Vary: Origin
172.25.122.135 X-Amz-Request-Id: 15C247AE6E24F7B3
172.25.122.135 X-Xss-Protection: 1; mode=block
172.25.122.135 Accept-Ranges: bytes
172.25.122.135 Content-Length: 128
172.25.122.135 Content-Security-Policy: block-all-mixed-content
172.25.122.135 <?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>
172.25.122.135
172.25.122.135 [REQUEST s3.HeadBucket] 22:13:54.887
172.25.122.135 HEAD /patients/
172.25.122.135 Host: 172.25.122.135:9000
172.25.122.135 X-Amz-Date: 20190907T221355Z
172.25.122.135 Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
172.25.122.135 Accept-Encoding: gzip, deflate
172.25.122.135 Authorization: AWS4-HMAC-SHA256 Credential=EPN9OZC3LEG232WC072S/20190907/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=dec6a7c6f65478f00fd560b2fedd5ddbeb57d28977da86d9e70e413fe22e7e23
172.25.122.135 Content-Length: 0
172.25.122.135 User-Agent: MinIO (Microsoft Windows NT 10.0.17134.0;x86_64) minio-dotnet/1.0.9
172.25.122.135 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
172.25.122.135
172.25.122.135 [RESPONSE] [22:13:54.888] [ Duration 861µs  🠉 100 B  🠋 218 B ]
172.25.122.135 200 OK
172.25.122.135 Content-Length: 0
172.25.122.135 Content-Security-Policy: block-all-mixed-content
172.25.122.135 Server: MinIO/RELEASE.2019-09-05T23-24-38Z
172.25.122.135 Vary: Origin
172.25.122.135 X-Amz-Request-Id: 15C247AE74C7ADBB
172.25.122.135 X-Xss-Protection: 1; mode=block
172.25.122.135 Accept-Ranges: bytes
172.25.122.135
172.25.122.135
172.25.122.135 [REQUEST s3.NewMultipartUpload] 22:13:55.241
172.25.122.135 POST /patients/1839e094894c4c5ba64b68b22409d0b5.dat?uploads
172.25.122.135 Host: 172.25.122.135:9000
172.25.122.135 Content-Length: 0
172.25.122.135 User-Agent: MinIO (Microsoft Windows NT 10.0.17134.0;x86_64) minio-dotnet/1.0.9
172.25.122.135 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
172.25.122.135 X-Amz-Date: 20190907T221355Z
172.25.122.135 Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
172.25.122.135 Authorization: AWS4-HMAC-SHA256 Credential=EPN9OZC3LEG232WC072S/20190907/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=42b68a5739dd34b2d504e74936681660d46d99e82e965e323424a81b5e7752d1
172.25.122.135 Content-Type: application/pdf
172.25.122.135 Accept-Encoding: gzip, deflate
172.25.122.135
172.25.122.135 [RESPONSE] [22:13:55.245] [ Duration 3.107ms  🠉 113 B  🠋 529 B ]
172.25.122.135 200 OK
172.25.122.135 Vary: Origin
172.25.122.135 X-Amz-Request-Id: 15C247AE89E778BF
172.25.122.135 X-Xss-Protection: 1; mode=block
172.25.122.135 Accept-Ranges: bytes
172.25.122.135 Content-Length: 279
172.25.122.135 Content-Security-Policy: block-all-mixed-content
172.25.122.135 Content-Type: application/xml
172.25.122.135 Server: MinIO/RELEASE.2019-09-05T23-24-38Z
172.25.122.135 <?xml version="1.0" encoding="UTF-8"?>
<InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>patients</Bucket><Key>1839e094894c4c5ba64b68b22409d0b5.dat</Key><UploadId>01a1ec9b-68c7-420a-8dbe-d83026e85d16</UploadId></InitiateMultipartUploadResult>
172.25.122.135
172.25.122.135 [REQUEST s3.PutObjectPart] 22:13:55.610
172.25.122.135 PUT /patients/1839e094894c4c5ba64b68b22409d0b5.dat?uploadId=01a1ec9b-68c7-420a-8dbe-d83026e85d16&partNumber=1
172.25.122.135 Host: 172.25.122.135:9000
172.25.122.135 Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
172.25.122.135 X-Amz-Content-Sha256: 7e32c459a50e61d03afb4f3b3b580bacd677875430ab14255b723b60414e6b26
172.25.122.135 Accept-Encoding: gzip, deflate
172.25.122.135 Authorization: AWS4-HMAC-SHA256 Credential=EPN9OZC3LEG232WC072S/20190907/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=e2a991c344076f1322935db440c06f1e03804bda6dbe127d0d07551106ee025d
172.25.122.135 Content-Length: 5242880
172.25.122.135 Content-Type: application/pdf
172.25.122.135 User-Agent: MinIO (Microsoft Windows NT 10.0.17134.0;x86_64) minio-dotnet/1.0.9
172.25.122.135 X-Amz-Date: 20190907T221356Z
172.25.122.135 <BODY>
172.25.122.135 [RESPONSE] [22:13:55.620] [ Duration 9.831ms  🠉 113 B  🠋 716 B ]
172.25.122.135 403 Forbidden
172.25.122.135 Content-Length: 459
172.25.122.135 Content-Security-Policy: block-all-mixed-content
172.25.122.135 Content-Type: application/xml
172.25.122.135 Server: MinIO/RELEASE.2019-09-05T23-24-38Z
172.25.122.135 Vary: Origin
172.25.122.135 X-Amz-Request-Id: 15C247AE9FDF3266
172.25.122.135 X-Xss-Protection: 1; mode=block
172.25.122.135 Accept-Ranges: bytes
172.25.122.135 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>1839e094894c4c5ba64b68b22409d0b5.dat</Key><BucketName>patients</BucketName><Resource>/patients/1839e094894c4c5ba64b68b22409d0b5.dat</Resource><RequestId>15C247AE9FDF3266</RequestId><HostId>468986af-d10d-4f25-93f2-6e3ee55f8d82</HostId></Error>
172.25.122.135
172.25.122.135 [REQUEST s3.DeleteObject] 22:13:56.036
172.25.122.135 DELETE /patients/1839e094894c4c5ba64b68b22409d0b5.dat
172.25.122.135 Host: 172.25.122.135:9000
172.25.122.135 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
172.25.122.135 X-Amz-Date: 20190907T221356Z
172.25.122.135 Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
172.25.122.135 Accept-Encoding: gzip, deflate
172.25.122.135 Authorization: AWS4-HMAC-SHA256 Credential=EPN9OZC3LEG232WC072S/20190907/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=7ac23d3d7fca14b5103f0d1ffb72ba28989b107bcb8a51068cf15d95efcd7e70
172.25.122.135 Content-Length: 0
172.25.122.135 User-Agent: MinIO (Microsoft Windows NT 10.0.17134.0;x86_64) minio-dotnet/1.0.9
172.25.122.135
172.25.122.135 [RESPONSE] [22:13:56.036] [ Duration 693µs  🠉 100 B  🠋 226 B ]
172.25.122.135 204 No Content
172.25.122.135 X-Amz-Request-Id: 15C247AEB93C6D60
172.25.122.135 X-Xss-Protection: 1; mode=block
172.25.122.135 Accept-Ranges: bytes
172.25.122.135 Content-Length: 0
172.25.122.135 Content-Security-Policy: block-all-mixed-content
172.25.122.135 Server: MinIO/RELEASE.2019-09-05T23-24-38Z
172.25.122.135 Vary: Origin
172.25.122.135
172.25.122.135
```


FIDDLER TRACE OF HTTP COMUNICATION (HEADERS ONLY):
-------------------------------------------------------------------

1'st request
--------------

```
POST http://172.25.122.135:9000/patients/c43d94fb399845348b6d2e35a2736111.dat?uploads HTTP/1.1
Content-Type: application/pdf
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20190907T221648Z
Authorization: AWS4-HMAC-SHA256 Credential=EPN9OZC3LEG232WC072S/20190907/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=f42ed2ab8786d147adaaa8bcf019382ab73ef64e6faf44ac2b4b33bd6c2cd182
Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
User-Agent: MinIO (Microsoft Windows NT 10.0.17134.0;x86_64) minio-dotnet/1.0.9
Host: 172.25.122.135:9000
Content-Length: 0
Accept-Encoding: gzip, deflate


HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 279
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO/RELEASE.2019-09-05T23-24-38Z
Vary: Origin
X-Amz-Request-Id: 15C247D6D66A6A79
X-Xss-Protection: 1; mode=block
Date: Sat, 07 Sep 2019 22:16:48 GMT
```

2'nd request
---------------

```
PUT http://172.25.122.135:9000/patients/c43d94fb399845348b6d2e35a2736111.dat?uploadId=1f32eaf2-9029-4ed1-be49-691673ea5d91&partNumber=1 HTTP/1.1
x-amz-content-sha256: 7e32c459a50e61d03afb4f3b3b580bacd677875430ab14255b723b60414e6b26
x-amz-date: 20190907T221648Z
Authorization: AWS4-HMAC-SHA256 Credential=EPN9OZC3LEG232WC072S/20190907/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=fa7436c1c5894c8b1668c97e5e3fbf5280065eec442b89b08f99ca0f59fa9086
Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
User-Agent: MinIO (Microsoft Windows NT 10.0.17134.0;x86_64) minio-dotnet/1.0.9
Content-Type: application/pdf
Host: 172.25.122.135:9000
Content-Length: 5242880
Accept-Encoding: gzip, deflate


HTTP/1.1 403 Forbidden
Accept-Ranges: bytes
Content-Length: 459
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO/RELEASE.2019-09-05T23-24-38Z
Vary: Origin
X-Amz-Request-Id: 15C247D6DE704B7A
X-Xss-Protection: 1; mode=block
Date: Sat, 07 Sep 2019 22:16:48 GMT
Connection: close
```

**Comment by Praveenrajmani** [comment]
I think this issue has to be moved to minio-dotnet @kannappanr
