### ISSUE TITLE
Uploading large files fails with 'One or more of the specified parts could not be found'

### ISSUE THREAD

**Issue by gsudhas** [minio/minio#8147]
Found an issue with uploading large files on a system running RHEL 7.6.

Created a large file (7GB) and tried uploading using mc. There were 56 parts which seemed to have uploaded correctly, but after that point the failure crops up:

mc cp /mnt/tmp/myuser/tmp.7g myminio/backup1
...
....
/mnt/tmp/myuser/tmp.7g:        6.99 GiB / 7.00 GiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃  99.90% 204.72 MiB/smc: <DEBUG> PUT /backup1/tmp.7g?partNumber=55&uploadId=ebca5f4c-7c30-403e-b8d0-4ecc7a45e352 HTTP/1.1
Host: 128.162.247.102:9000
User-Agent: MinIO (linux; amd64) minio-go/v6.0.32 mc/2019-08-21T19:59:10Z
Content-Length: 134402134
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20190829/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=**REDACTED**
X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
X-Amz-Date: 20190829T023602Z
X-Amz-Decoded-Content-Length: 134217728
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 0
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Thu, 29 Aug 2019 02:36:04 GMT
Etag: "0bf065e632a20ca09daac15563f8255d-1"
Server: MinIO/RELEASE.2019-08-21T19-40-07Z
Vary: Origin
X-Amz-Request-Id: 15BF442EB811274E
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  1.827778985s

/mnt/tmp/myuser/tmp.7g:        7.00 GiB / 7.00 GiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 204.19 MiB/smc: <DEBUG> PUT /backup1/tmp.7g?partNumber=56&uploadId=ebca5f4c-7c30-403e-b8d0-4ecc7a45e352 HTTP/1.1
Host: 128.162.247.102:9000
User-Agent: MinIO (linux; amd64) minio-go/v6.0.32 mc/2019-08-21T19:59:10Z
Content-Length: 134402134
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20190829/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=**REDACTED**
X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
X-Amz-Date: 20190829T023603Z
X-Amz-Decoded-Content-Length: 134217728
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 0
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Thu, 29 Aug 2019 02:36:04 GMT
Etag: "e6848b3597483e44adda8dac257a3659-1"
Server: MinIO/RELEASE.2019-08-21T19-40-07Z
Vary: Origin
X-Amz-Request-Id: 15BF442ED0A99DB9
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  1.555324229s

mc: <DEBUG> POST /backup1/tmp.7g?uploadId=ebca5f4c-7c30-403e-b8d0-4ecc7a45e352 HTTP/1.1
Host: 128.162.247.102:9000
User-Agent: MinIO (linux; amd64) minio-go/v6.0.32 mc/2019-08-21T19:59:10Z
Content-Length: 7650
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20190829/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: 80fc7266265ef5df39c4ad2e99b027929c81787b0107e7d7fdd6d8fd20a1f5dc
X-Amz-Date: 20190829T023604Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 400 Bad Request
Content-Length: 435
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 29 Aug 2019 02:36:04 GMT
Server: MinIO/RELEASE.2019-08-21T19-40-07Z
Vary: Origin
X-Amz-Request-Id: 15BF442F2D632A63
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidPart</Code><Message>One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part&#39;s entity tag.</Message><Key>tmp.7g</Key><BucketName>backup1</BucketName><Resource>/backup1/tmp.7g</Resource><RequestId>15BF442F2D632A63</RequestId><HostId>9259697f-faf4-4103-8845-7003848acaeb</HostId></Error>mc: <DEBUG> Response Time:  3.371001ms

/mnt/tmp/myuser/tmp.7g:        7.00 GiB / 7.00 GiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 203.47 MiB/smc: <DEBUG> DELETE /backup1/tmp.7g?uploadId=ebca5f4c-7c30-403e-b8d0-4ecc7a45e352 HTTP/1.1
Host: 128.162.247.102:9000
User-Agent: MinIO (linux; amd64) minio-go/v6.0.32 mc/2019-08-21T19:59:10Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20190829/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190829T023604Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 204 No Content
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Thu, 29 Aug 2019 02:36:04 GMT
Server: MinIO/RELEASE.2019-08-21T19-40-07Z
Vary: Origin
X-Amz-Request-Id: 15BF442F2D97AA2D
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  42.51005ms

mc: <ERROR> Failed to copy `/mnt/tmp/myuser/tmp.7g`. One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.
 (3) cp-main.go:425 cmd.doCopySession(..) Tags: [/mnt/tmp/myuser/tmp.7g]
 (2) common-methods.go:289 cmd.uploadSourceToTargetURL(..) Tags: [http://128.162.247.102:9000/backup1/tmp.7g]
 (1) common-methods.go:178 cmd.putTargetStream(..) Tags: [myminio, http://128.162.247.102:9000/backup1/tmp.7g]
 (0) client-s3.go:853 cmd.(*s3Client).Put(..)
 Release-Tag:RELEASE.2019-08-21T19-59-10Z | Commit:89d30e9aa288 | Host:augusta.eag.rdlabs.hpecorp.net | OS:linux | Arch:amd64 | Lang:go1.12.8 | Mem:232 MB/1.0 GB | Heap:232 MB/1.0 GB
mc: <ERROR> Session safely terminated. To resume session `mc session resume iCzDFXvh`

Could someone help in debugging this?

I tried to do multipart upload using boto and hit the same error when completing the multipart upload.  Any help would be greatly appreciated.

**Comment by harshavardhana** [comment]
This bug was fixed and released - refer #8142

**Comment by gsudhas** [comment]
This issue is still seen with the latest build of minio and mc. Could you please recheck the results for uploading a large file?

**Comment by harshavardhana** [comment]
Are you sure you upgraded all servers ? Also are you using a distributed setup here ?

**Comment by gsudhas** [comment]
It is just a simple one node setup. I used the latest source code and used the newly built minio and mc for the test.

**Comment by harshavardhana** [comment]
Okay then it's a different issue..

**Comment by krishnasrinivas** [comment]
@gsudhas is the backend FS a local XFS/ext4 or NFS?

**Comment by gsudhas** [comment]
The backend is a cluster XFS. I just tried using ext4 filesystem as a backend and there are no issues!
