### ISSUE TITLE
mc admin update not working!

### ISSUE THREAD

**Issue by daltonthedog** [minio/minio#8479]
After release "minio.RELEASE.2019-10-11T00-38-09Z"(inclusive), `mc admin update` is not working anymore, output is:
`mc: <ERROR> Unable to update the server. The specified method is not allowed against this resource.
`
## Steps to Reproduce
```
[root@dalton bin]# wget https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2019-10-02T21-19-38Z -O minio
--2019-11-02 05:26:10--  https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2019-10-02T21-19-38Z
Resolving dl.min.io (dl.min.io)... 178.128.69.202
Connecting to dl.min.io (dl.min.io)|178.128.69.202|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 43782144 (42M) [application/octet-stream]
Saving to: ‘minio’

100%[=================================================================================================================================================================>] 43,782,144  4.57MB/s   in 12s

2019-11-02 05:26:28 (3.58 MB/s) - ‘minio’ saved [43782144/43782144]

[root@dalton bin]# chmod +x minio
[root@dalton bin]# service minio start
Redirecting to /bin/systemctl start minio.service
[root@dalton bin]# ./mc admin update minio
Server `minio` updated successfully from 2019-10-02T21:19:38Z to 2019-10-12T01-39-57Z
[root@dalton bin]#
[root@dalton bin]#
[root@dalton bin]# ./mc admin update minio
mc: <ERROR> Unable to update the server. The specified method is not allowed against this resource.

```
## Your Environment
Binaries tested:
minio.RELEASE.2019-10-02T21-19-38Z  -> working
minio.RELEASE.2019-10-11T00-38-09Z -> not working
minio.RELEASE.2019-10-12T01-39-57Z -> not working
lastest (2019-10-11 00:39) -> not working

Tested on centos 7
Linux dalton 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Edit: 
`
mc version RELEASE.2019-10-09T22-54-57Z
`

**Comment by nitisht** [comment]
What is you `mc` version @daltonthedog

**Comment by daltonthedog** [comment]
> 
> 
> What is you `mc` version @daltonthedog

```
[root@dalton bin]# ./mc -version
mc version RELEASE.2019-10-09T22-54-57Z
[root@dalton bin]# ./mc update
You are already running the most recent version of ‘mc’.
```

**Comment by harshavardhana** [comment]
Yes there was a bug we fixed it in master, restart your server with MINIO_UPDATE=on env and it shall work as workaround for now.

**Comment by harshavardhana** [comment]
Closing this as fixed in master

**Comment by miksonx** [comment]
Hi,
After making manual upgrade of the latest version of minio and setting up env variable as described the update is still not working

./mc admin update myminio
mc: <ERROR> Unable to update the server. The specified method is not allowed against this resource.

Server:
VERSION
2019-10-12T01:39:57Z

./mc --version
mc version RELEASE.2019-10-09T22-54-57Z

./mc update
You are already running the most recent version of ‘mc’.

**Comment by harshavardhana** [comment]
@miksonx looks like you haven't set the ENV properly 

```
~ MINIO_UPDATE=on minio server ~/test
Endpoint:  http://10.0.0.17:9000  http://172.17.0.1:9000  http://127.0.0.1:9000          
AccessKey: minio 
SecretKey: minio123 
Region:    us-east-1
```

```
~ mc admin update myminio
Server `myminio` already running the most recent version 2019-10-12T01:39:57Z of MinIO
```
