### ISSUE TITLE
[GATEWAY] wrong name mapping when using custom azure endpoint

### ISSUE THREAD

**Issue by bottkars** [minio/minio#8585]
when starting minio with a custom azure Endpoint per documentation,
```
minio gateway azure https://azureaccountname.blob.custom.azure.endpoint
```
then minio adds a duplicate accountkey and blob to the URL.
as mini constructs the endpoint from 
This may be because the code wants to create the endpoint from a custom suffix, where minio gateway expects an resolvable fqdn

#### Scenario 1
use blob url as custom endpoint as per docu
```
MINI0_CUSTOMENDPOINT="https://minio.blob.sc2.azurestack-rd.cf-app.com"minio gateway azure $MINI0_CUSTOMENDPOINT 
Endpoint:  http://10.255.212.30:9000  http://10.200.100.8:9000  http://127.0.0.1:9000 ...
```
minio starts as expected, however, bucket operations fail:
```
error: Get https://minio.blob.minio.blob.sc2.azurestack-rd.cf-app.com/?comp=list: x509: certificate is valid for *.sc2.azurestack-rd.cf-app.com, *.blob.sc2.azurestack-rd.cf-app.com, *.queue.sc2.azurestack-rd.cf-app.com, *.table.sc2.azurestack-rd.cf-app.com, *.vault.sc2.azurestack-rd.cf-app.com, *.adminvault.sc2.azurestack-rd.cf-app.com, *.adminhosting.sc2.azurestack-rd.cf-app.com, *.hosting.sc2.azurestack-rd.cf-app.com, portal.sc2.azurestack-rd.cf-app.com, adminportal.sc2.azurestack-rd.cf-app.com, management.sc2.azurestack-rd.cf-app.com, adminmanagement.sc2.azurestack-rd.cf-app.com, sc2.azurestack-rd.cf-app.com, blob.sc2.azurestack-rd.cf-app.com, queue.sc2.azurestack-rd.cf-app.com, table.sc2.azurestack-rd.cf-app.com, vault.sc2.azurestack-rd.cf-app.com, adminvault.sc2.azurestack-rd.cf-app.com, adminhosting.sc2.azurestack-rd.cf-app.com, hosting.sc2.azurestack-rd.cf-app.com, **not minio.blob.minio.blob.sc2.azurestack-rd.cf-app.com**
```
by looking at the bucket construct, minio looks for *minio.blob.minio.blob.sc2.azurestack-rd.cf-app.com* instead of *minio.blob.sc2.azurestack-rd.cf-app.com*

### Scenario 2
use endpoint suffix ( preferred solution ) as custom endpoint
if using the endpoint suffix as fqdn, minio refuses to start 
```
MINI0_CUSTOMENDPOINT="https://sc2.azurestack-rd.cf-app.com"minio gateway azure $MINI0_CUSTOMENDPOINT
ERROR Invalid argument: lookup sc2.azurestack-rd.cf-app.com on 10.70.0.10:53: no such host
``` 
this is because of:
https://github.com/minio/minio/blob/2ff8132e2df51c4c5d2b080b7898112efa729b11/cmd/gateway/azure/gateway-azure.go#L163-L167
Possible Workaround: put an resolvable ip for the custom suffix in local hosts file:
minio starts, bucket operations work, uploads and downloads with no issue

## Possible Solution

1. Do not try to resolve custom suffix upon start, as the code constructs the endpoint from suffix.
try to resolve storageaccount.blob.endpoint

2. Modify the help file to specify endpoint suffix instead of endpoint 

## Steps to Reproduce (for bugs)

1. Call Minio with and existing azure bucket and the public endpoint should NOT bring the same error,
as you strip endpoint i equal core.windows.net
Setup azure with a custom domain, or:
2. Try on AzureStack :-)

## Context

not able to run minio gateway against azurestack !

## Your Environment

* Version used (`minio version`):
Version: 2019-10-12T01:39:57Z
Release-Tag: RELEASE.2019-10-12T01-39-57Z
Commit-ID: bd106408462ecef70debf51f1e6179de950c5812
* Server type and version:
* Operating System and version (`uname -a`):
19.0.0 Darwin Kernel Version 19.0.0
* Link to your project:

**Comment by harshavardhana** [comment]
This is fixed in master branch PTAL, closing as fixed.

**Comment by bottkars** [comment]
I will build the packages for a Test. Have seen you also moved towards blobapi and need to check for stack compatibility!

Von meinem iPhone gesendet

Am 02.12.2019 um 18:34 schrieb Harshavardhana <notifications@github.com>:

﻿

This is fixed in master branch PTAL, closing as fixed.

**Comment by bottkars** [comment]
unfortunately, the endpoint check behaviour is still the same, you try to check a domain as hostname .
In case of Azurestack, the blob url is storageaccount.blob.region.customdomainname. 

Depending on the service type ( Database, Blob, Table  etc) that will generate a wildcard DNS for *.servicetype.endpoint 

for examle : 
REGION = SC2
SERVICE=BLOB
STORAGERACCOUNT=minio
DOMAIN: azurestack-rd.cf-app.com

The Blob endpoint for that Storageaccount would be https://minio.blob.sc2.azurestack-rd.cf-app.com
*.blob.sc2.azurestack-rd.cf-app.com prepresnts a wildcard DNS Label that could be tested with 
nslookup anything.blob.sc2.azurestack-rd.cf-app.com and will resolve the *.blob.sc2.azurestack-rd.cf-app.com label.


The new change to the blob sdk also introduces a major downside: it will no longer work with AzureStack.

As there may be a valid reason to use the BLOB sdk,  however, i did not find any reference to use it with azurestack. 
Microsoft refers to use the azure-sdk-for-go and autorest, at least in the azurestack documentation.
that works well, an the minio release RELEASE.2019-10-12T01-39-57Z works fine with that.


The current master branch would break AZURESTACK completely.

Happy to pair for a remote session to elaborate in Detail

**Comment by harshavardhana** [comment]
Looks like @c-w would need to see if this got broken in this PR

https://github.com/minio/minio/commit/947bc8c7d3b8ad98cdbb6ce0f8dea155df16aadf

**Comment by c-w** [comment]
> unfortunately, the endpoint check behaviour is still the same, you try to check a domain as hostname . In case of Azurestack, the blob url is storageaccount.blob.region.customdomainname.

I believe the endpoint parsing should work correctly since https://github.com/minio/minio/pull/8537 was merged; see the tests in [TestParseStorageEndpoint](https://github.com/minio/minio/blob/d2dc964cb5a3465fc6d052d76d773ea838590bdb/cmd/gateway/azure/gateway-azure_test.go#L31-L57) where the second test-case for Azure Government should be equivalent for the required behavior for Azure Stack (also confirmed by a manual [test run with the Azure Stack example](https://user-images.githubusercontent.com/1086421/70283619-957f2280-180d-11ea-8c7d-c3207df8954f.png)). Could you clarify what behavior are you expecting here, @bottkars?

> The new change to the blob sdk also introduces a major downside: it will no longer work with AzureStack.

One key difference between Azure Storage and Azure Stack Storage is that I tested the former with StorageV2 accounts and the latter only supports StorageV1 accounts ([see docs](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-acs-differences#cheat-sheet-storage-differences)). However, I just did some cursory testing of a cloud-based StorageV1 account using the MinIO browser and everything seems to be working fine.

The azure-storage-blob-go SDK and azure-sdk-for-go ultimately call the same REST API endpoints. The main difference is that the new SDK uses API version 2018-11-09 ([see code](https://github.com/Azure/azure-storage-blob-go/blob/3efca72bd11c050222deab57e25ea90df03b9692/azblob/zz_generated_client.go#L12-L13)) and the old SDK uses API version 2018-03-28 ([see code](https://github.com/Azure/azure-sdk-for-go/blob/e56ec3f142bfbc83f619f7e7eaf72abf03a3ef17/storage/client.go#L47-L49)), none of which seem explicitly supported by Azure Stack ([see docs](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-acs-differences#api-version)) so if this worked previously it was coincidental.

Could you share exactly which operations are failing against your Azure Stack Storage endpoint using the azure-storage-blob-go SDK and what are the error messages?

**Comment by harshavardhana** [comment]
@bottkars can you reply to @c-w ? -if we don't hear back from you we shall close this issue in couple of more days.

**Comment by bottkars** [comment]
Point 1, the name lookup/creation / testing, now seems to work.
However, as i stated earlier, the API Versions DO NOT work with AzureStack.
The API Version used with the AzureSDKforGO was not 2018-03-28 as @c-w pointed out, it was 	2016-05-31" as set in you code ( https://github.com/minio/minio/blob/bd106408462ecef70debf51f1e6179de950c5812/cmd/gateway/azure/gateway-azure.go#L51 )

From that i would need go back to the old binaries ...

**Comment by bottkars** [comment]
just in case: this is the error when creating a bucket:
![image](https://user-images.githubusercontent.com/8255007/71547570-072c3580-29a2-11ea-8af6-64de9d6d1905.png)
Also, existing buckets and files are not read

**Comment by c-w** [comment]
@bottkars The maintainers of `azure-storage-blob-go` mention a way to force a specific storage API version ([see comment](https://github.com/Azure/azure-storage-blob-go/issues/86#issuecomment-433568881)) which I've ported to MinIO. Given that I don't have access to an Azure Stack deployment, could you test this and confirm whether or not this works for you?

```diff
diff --git a/cmd/gateway/azure/gateway-azure.go b/cmd/gateway/azure/gateway-azure.go
index e410c19..8bcd3d1 100644
--- a/cmd/gateway/azure/gateway-azure.go
+++ b/cmd/gateway/azure/gateway-azure.go
@@ -42,6 +42,7 @@ import (
 	"github.com/minio/minio/cmd"
 	"github.com/minio/minio/cmd/logger"
 	"github.com/minio/minio/pkg/auth"
+	"github.com/minio/minio/pkg/env"
 	"github.com/minio/minio/pkg/policy"
 	"github.com/minio/minio/pkg/policy/condition"
 	sha256 "github.com/minio/sha256-simd"
@@ -68,6 +69,8 @@ const (
 	azureMarkerPrefix          = "{minio}"
 	metadataPartNamePrefix     = minio.GatewayMinioSysTmp + "multipart/v1/%s.%x"
 	maxPartsCount              = 10000
+	azureStorageAPIEnvVar      = "AZURE_STORAGE_API_VERSION"
+	azureStorageAPIDefault     = "2018-11-09"
 )
 
 func init() {
@@ -84,9 +87,10 @@ ENDPOINT:
   Azure server endpoint. Default ENDPOINT is https://core.windows.net
 
 EXAMPLES:
-  1. Start minio gateway server for Azure Blob Storage backend on custom endpoint.
+  1. Start minio gateway server for Azure Blob Storage backend on custom endpoint and specific storage API version.
      {{.Prompt}} {{.EnvVarSetCommand}} MINIO_ACCESS_KEY{{.AssignmentOperator}}azureaccountname
      {{.Prompt}} {{.EnvVarSetCommand}} MINIO_SECRET_KEY{{.AssignmentOperator}}azureaccountkey
+     {{.Prompt}} {{.EnvVarSetCommand}} AZURE_STORAGE_API_VERSION{{.AssignmentOperator}}2016-05-31
      {{.Prompt}} {{.HelpName}} https://azureaccountname.blob.custom.azure.endpoint
 
   2. Start minio gateway server for Azure Blob Storage backend with edge caching enabled.
@@ -148,6 +152,7 @@ func (g *Azure) NewGatewayLayer(creds auth.Credentials) (minio.ObjectLayer, erro
 
 	httpClient := &http.Client{Transport: minio.NewCustomHTTPTransport()}
 	userAgent := fmt.Sprintf("APN/1.0 MinIO/1.0 MinIO/%s", minio.Version)
+	storageAPIVersion := env.Get(azureStorageAPIEnvVar, azureStorageAPIDefault)
 
 	pipeline := azblob.NewPipeline(credential, azblob.PipelineOptions{
 		Retry: azblob.RetryOptions{
@@ -156,6 +161,7 @@ func (g *Azure) NewGatewayLayer(creds auth.Credentials) (minio.ObjectLayer, erro
 		HTTPSender: pipeline.FactoryFunc(func(next pipeline.Policy, po *pipeline.PolicyOptions) pipeline.PolicyFunc {
 			return func(ctx context.Context, request pipeline.Request) (pipeline.Response, error) {
 				request.Header.Set("User-Agent", userAgent)
+				request.Header.Set("x-ms-version", storageAPIVersion)
 				resp, err := httpClient.Do(request.WithContext(ctx))
 				return pipeline.NewHTTPResponse(resp), err
 			}
```

If that doesn't work, Azure Stack support will require downgrading the SDK to version 0.2.0 ([see version table](https://github.com/Azure/azure-storage-blob-go#version-table)), but pinning to such an old SDK version may not be wise for MinIO targeting cloud deployments of Azure Storage. As such, if Azure Stack support is an explicit requirement for MinIO, I'd recommend the team to reach out to the maintainers of `azure-storage-blob-go` to inquire about their plans for support of Azure Stack.

**Comment by bottkars** [comment]
i will give it a try, but will also reach out to the Azurestack Team on their plans for newer API Versions of (Blob) Storage

**Comment by bottkars** [comment]
i think @tombuildsstuff went thru hell with the GO SDK an thus, they built their own SDK  https://github.com/tombuildsstuff/giovanni . Having that said, it is not worth using an early version ...

**Comment by g13013** [comment]
I am getting this error inside docker

```
x509: certificate is valid for
```
the certificate is perfectly valid, using curl:

```
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
```

**Comment by vadmeste** [comment]
@g13013 this looks like a different issue, could you join https://slack.min.io and ask there ?

**Comment by harshavardhana** [comment]
> @bottkars The maintainers of `azure-storage-blob-go` mention a way to force a specific storage API version ([see comment](https://github.com/Azure/azure-storage-blob-go/issues/86#issuecomment-433568881)) which I've ported to MinIO. Given that I don't have access to an Azure Stack deployment, could you test this and confirm whether or not this works for you?
> 
> ```diff
> diff --git a/cmd/gateway/azure/gateway-azure.go b/cmd/gateway/azure/gateway-azure.go
> index e410c19..8bcd3d1 100644
> --- a/cmd/gateway/azure/gateway-azure.go
> +++ b/cmd/gateway/azure/gateway-azure.go
> @@ -42,6 +42,7 @@ import (
>  	"github.com/minio/minio/cmd"
>  	"github.com/minio/minio/cmd/logger"
>  	"github.com/minio/minio/pkg/auth"
> +	"github.com/minio/minio/pkg/env"
>  	"github.com/minio/minio/pkg/policy"
>  	"github.com/minio/minio/pkg/policy/condition"
>  	sha256 "github.com/minio/sha256-simd"
> @@ -68,6 +69,8 @@ const (
>  	azureMarkerPrefix          = "{minio}"
>  	metadataPartNamePrefix     = minio.GatewayMinioSysTmp + "multipart/v1/%s.%x"
>  	maxPartsCount              = 10000
> +	azureStorageAPIEnvVar      = "AZURE_STORAGE_API_VERSION"
> +	azureStorageAPIDefault     = "2018-11-09"
>  )
>  
>  func init() {
> @@ -84,9 +87,10 @@ ENDPOINT:
>    Azure server endpoint. Default ENDPOINT is https://core.windows.net
>  
>  EXAMPLES:
> -  1. Start minio gateway server for Azure Blob Storage backend on custom endpoint.
> +  1. Start minio gateway server for Azure Blob Storage backend on custom endpoint and specific storage API version.
>       {{.Prompt}} {{.EnvVarSetCommand}} MINIO_ACCESS_KEY{{.AssignmentOperator}}azureaccountname
>       {{.Prompt}} {{.EnvVarSetCommand}} MINIO_SECRET_KEY{{.AssignmentOperator}}azureaccountkey
> +     {{.Prompt}} {{.EnvVarSetCommand}} AZURE_STORAGE_API_VERSION{{.AssignmentOperator}}2016-05-31
>       {{.Prompt}} {{.HelpName}} https://azureaccountname.blob.custom.azure.endpoint
>  
>    2. Start minio gateway server for Azure Blob Storage backend with edge caching enabled.
> @@ -148,6 +152,7 @@ func (g *Azure) NewGatewayLayer(creds auth.Credentials) (minio.ObjectLayer, erro
>  
>  	httpClient := &http.Client{Transport: minio.NewCustomHTTPTransport()}
>  	userAgent := fmt.Sprintf("APN/1.0 MinIO/1.0 MinIO/%s", minio.Version)
> +	storageAPIVersion := env.Get(azureStorageAPIEnvVar, azureStorageAPIDefault)
>  
>  	pipeline := azblob.NewPipeline(credential, azblob.PipelineOptions{
>  		Retry: azblob.RetryOptions{
> @@ -156,6 +161,7 @@ func (g *Azure) NewGatewayLayer(creds auth.Credentials) (minio.ObjectLayer, erro
>  		HTTPSender: pipeline.FactoryFunc(func(next pipeline.Policy, po *pipeline.PolicyOptions) pipeline.PolicyFunc {
>  			return func(ctx context.Context, request pipeline.Request) (pipeline.Response, error) {
>  				request.Header.Set("User-Agent", userAgent)
> +				request.Header.Set("x-ms-version", storageAPIVersion)
>  				resp, err := httpClient.Do(request.WithContext(ctx))
>  				return pipeline.NewHTTPResponse(resp), err
>  			}
> ```
> 
> If that doesn't work, Azure Stack support will require downgrading the SDK to version 0.2.0 ([see version table](https://github.com/Azure/azure-storage-blob-go#version-table)), but pinning to such an old SDK version may not be wise for MinIO targeting cloud deployments of Azure Storage. As such, if Azure Stack support is an explicit requirement for MinIO, I'd recommend the team to reach out to the maintainers of `azure-storage-blob-go` to inquire about their plans for support of Azure Stack.

The issue seems to have gone stale with no updates since 2019 closing this issue. Please re-open if the issue is still valid.

**Comment by bottkars** [comment]
hey ! Good news ! Microsoft release AzureSTack 2005, thatnow supports Azure Storage services APIs version 2019-02-02. For Azure client libraries, that is compatible with the new REST API version. For more information, see Azure Stack Hub storage development tools.

**Comment by vennilashanthi** [comment]
Hi @bottkars , @harshavardhana , @c-w 
Is the issue resolved ?  When starting minio with a custom azure Endpoint as per documentation,
`minio gateway azure https://azureaccountname.blob.custom.azure.endpoint`  is not seems to working for me.

Minio version : 
```
./minio --version
minio version RELEASE.2020-10-28T08-16-50Z
```
Operating System:
```
## uname -a
Linux minio-xaas 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
## cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)
```

Error which I'm getting is,
![image](https://user-images.githubusercontent.com/74044261/98344044-b44af200-2038-11eb-9e7e-f3d0c2bd645e.png)

could you please let me know how to resolve this?

**Comment by vadmeste** [comment]
@vennilashanthi what's your AzureStack version ?

**Comment by vennilashanthi** [comment]
@vadmeste 
Thanks for responding....

It's Stamp:-1.2002.53.144

**Comment by vadmeste** [comment]
@vennilashanthi according to comments in this issue, you need AzureStack 2005. I really don't have the bandwidth to test this though.

**Comment by vennilashanthi** [comment]
@vadmeste ,  Thanks !!!

Could anyone please confirm that it's working in AzureStack 2005?

**Comment by bottkars** [comment]
confirmed. use the endpoint name, n0t the blob address:
export MINIO_ACCESS_KEY="minio" <-- account name
export MINIO_SECRET_KEY="secret key"
minio gateway --config-dir $CONFIG_DIR \
         --address ':9000' azure 'https://custom.azure.endpoint'

**Comment by vennilashanthi** [comment]
Thanks @bottkars , Let me check.
