### ISSUE TITLE
Panic after upgrading MinIO cluster

### ISSUE THREAD

**Issue by erhlee-bird** [minio/minio#9416]
We've been running a two node distributed cluster for some time, updating periodically. Upgrading from `minio.RELEASE.2020-02-27T00-23-05Z` to `minio version RELEASE.2020-04-15T19-42-18Z` caused an issue where one of the servers consistently panics while restarting.

Looking through the changelog, I see that there are breaking changes so I reverted successfully to `minio.RELEASE.2020-02-27T00-23-05Z` and incrementally upgraded up to `minio.RELEASE.2020-03-25T07-03-04Z` or the release one before without issue. 

Attempts to upgrade to any release version beyond starting from `minio.RELEASE.2020-04-02T21-34-49Z` fails with the error as originally described.

## Expected Behavior

Successful cluster upgrade.

## Current Behavior

```
Apr 20 13:06:31 ch09 minio[3245965]: panic: runtime error: index out of range [1] with length 0
Apr 20 13:06:31 ch09 minio[3245965]: goroutine 1 [running]:
Apr 20 13:06:31 ch09 minio[3245965]: github.com/minio/minio/cmd.newXLSets(0x202d2a0, 0xc00010e000, 0xc00015a800, 0x168, 0x180, 0xc007d02000, 0x168, 0x168, 0xc0060f6780, 0x1e, ...)
Apr 20 13:06:31 ch09 minio[3245965]:         github.com/minio/minio@/cmd/xl-sets.go:353 +0x115d
Apr 20 13:06:31 ch09 minio[3245965]: github.com/minio/minio/cmd.newXLZones(0x202d2a0, 0xc00010e000, 0xc0005fa270, 0x1, 0x1, 0xc000757590, 0x8, 0x180, 0x150d408)
Apr 20 13:06:31 ch09 minio[3245965]:         github.com/minio/minio@/cmd/xl-zones.go:77 +0x34a
Apr 20 13:06:31 ch09 minio[3245965]: github.com/minio/minio/cmd.newObjectLayer(0x202d2a0, 0xc00010e000, 0xc0005fa270, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
Apr 20 13:06:31 ch09 minio[3245965]:         github.com/minio/minio@/cmd/server-main.go:490 +0xfc
Apr 20 13:06:31 ch09 minio[3245965]: github.com/minio/minio/cmd.serverMain(0xc000112b60)
Apr 20 13:06:31 ch09 minio[3245965]:         github.com/minio/minio@/cmd/server-main.go:415 +0x8c6
Apr 20 13:06:31 ch09 minio[3245965]: github.com/minio/cli.HandleAction(0x18f12a0, 0x1cf4cb8, 0xc000112b60, 0xc00010c800, 0x0)
Apr 20 13:06:31 ch09 minio[3245965]:         github.com/minio/cli@v1.22.0/app.go:500 +0x7c
Apr 20 13:06:31 ch09 minio[3245965]: github.com/minio/cli.Command.Run(0x1c6316f, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1c8b831, 0x1b, 0x0, ...)
Apr 20 13:06:31 ch09 minio[3245965]:         github.com/minio/cli@v1.22.0/command.go:225 +0x991
Apr 20 13:06:31 ch09 minio[3245965]: github.com/minio/cli.(*App).Run(0xc0001121a0, 0xc000110000, 0x5, 0x5, 0x0, 0x0)
Apr 20 13:06:31 ch09 minio[3245965]:         github.com/minio/cli@v1.22.0/app.go:261 +0x6ab
Apr 20 13:06:31 ch09 minio[3245965]: github.com/minio/minio/cmd.Main(0xc000110000, 0x5, 0x5)
Apr 20 13:06:31 ch09 minio[3245965]:         github.com/minio/minio@/cmd/main.go:169 +0x89
Apr 20 13:06:31 ch09 minio[3245965]: main.main()
Apr 20 13:06:31 ch09 minio[3245965]:         github.com/minio/minio@/main.go:37 +0x45
```
## Steps to Reproduce (for bugs)

I'm uncertain, I posted the release versions above and 1 other member of the Slack community commented that they could replicate this error for a single node deployment.

## Context

I've been running this cluster since sometime in September last year.

```
    "backend": {
      "backendType": "Erasure",
      "onlineDisks": 360,
      "rrSCData": 10,
      "rrSCParity": 2,
      "standardSCData": 6,
      "standardSCParity": 6
    },
```

Each drive set is configured for a set of 12 drives. That was how whatever version of MinIO I initially started with configured the sets. I only recently had to specify an environment variable to match this setting.

`MINIO_ERASURE_SET_DRIVE_COUNT=12`

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

Versions listed above.
Distributed cluster with 2 nodes.
Ubuntu 18.04

**Comment by kannappanr** [comment]
@erhlee-bird Can you also paste the command you use to start the MinIO server?

**Comment by erhlee-bird** [comment]
```
[Unit]
Description=MinIO
Documentation=https://docs.min.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio

[Service]
WorkingDirectory=/usr/local

User=minio-user
Group=minio-user

EnvironmentFile=-/etc/default/minio
ExecStartPre=/bin/bash -c "if [ -z \"${MINIO_VOLUMES}\" ]; then echo \"Variable MINIO_VOLUMES not set in /etc/default/minio\"; exit 1; fi"
ExecStartPre=/bin/bash -c "if [ -z \"${MINIO_ACCESS_KEY}\" ]; then echo \"Variable MINIO_ACCESS_KEY not set in /etc/default/minio\"; exit 1; fi"
ExecStartPre=/bin/bash -c "if [ -z \"${MINIO_SECRET_KEY}\" ]; then echo \"Variable MINIO_SECRET_KEY not set in /etc/default/minio\"; exit 1; fi"

ExecStart=/usr/local/bin/minio server $MINIO_OPTS $MINIO_VOLUMES

# Let systemd restart this service always
Restart=always

# Specifies the maximum file descriptor number that can be opened by this process
LimitNOFILE=65536

# Disable timeout logic and wait until process is stopped
TimeoutStopSec=infinity
SendSIGKILL=no

[Install]
WantedBy=multi-user.target

# Built for ${project.name}-${project.version} (${project.name})
```

I have it running as a systemd unit with the above

**Comment by erhlee-bird** [comment]
I think I got it from here: https://github.com/minio/minio-service/blob/master/linux-systemd/minio.service

**Comment by erhlee-bird** [comment]
```
MINIO_VOLUMES=https://minio-{1...2}:9000/mnt/disk{1...180}
MINIO_OPTS="--certs-dir /srv/minio"
MINIO_ACCESS_KEY="xxx"
MINIO_SECRET_KEY="xxx"
MINIO_UPDATE=on
MINIO_ERASURE_SET_DRIVE_COUNT=12
```

**Comment by harshavardhana** [comment]
> Each drive set is configured for a set of 12 drives. That was how whatever version of MinIO I initially started with configured the sets. I only recently had to specify an environment variable to match this setting.
> 
> `MINIO_ERASURE_SET_DRIVE_COUNT=12`

This is because we have started supporting an Odd number of drives so for your setup new erasure set ratio is 15, there is another feature that is pending is to provide symmetric affinity based on the number of nodes provided.

We shall be adding that feature soon which should make your cluster 12 to be expected default for symmetric setup.

How easy it is to reproduce the crash? it looks like 

> MINIO_ERASURE_SET_DRIVE_COUNT=12

Is not set on one of the hosts.

**Comment by erhlee-bird** [comment]
@harshavardhana the settings are identical for the 2 boxes and that specific setting is present on both.

When I was missing that setting on either host, I would get an entirely different error at bootup saying that the sets could not be configured for 15 drives as the existing formatting was for 12 drives.

**Comment by harshavardhana** [comment]
> @harshavardhana the settings are identical for the 2 boxes and that specific setting is present on both.
> 
> When I was missing that setting on either host, I would get an entirely different error at bootup saying that the sets could not be configured for 15 drives as the existing formatting was for 12 drives.

Correct is the crash still present, because I can't reproduce it locally..

**Comment by erhlee-bird** [comment]
It is, I've been unable to upgrade from `minio.RELEASE.2020-03-25T07-03-04Z`.

And as I mentioned, there's another user from Slack who had confirmed a crash upgrading from the same version.

**Comment by harshavardhana** [comment]
> It is, I've been unable to upgrade from `minio.RELEASE.2020-03-25T07-03-04Z`.
> 
> And as I mentioned, there's another user from Slack who had confirmed a crash upgrading from the same version.

I can't seem to see how is that possible, unless with incorrect settings. Let me check.

**Comment by erhlee-bird** [comment]
I've been using the same settings to drive a working cluster since last September.

The only setting that's been added is the `MINIO_ERASURE_SET_DRIVE_COUNT` and it's on both servers.

The user commented that he experienced the same error in a 1 node setup.

**Comment by harshavardhana** [comment]
Potential fix available in #9446

**Comment by erhlee-bird** [comment]
Can we reopen this, I'm still seeing the same panic in `RELEASE.2020-04-28T23-56-56Z`

**Comment by harshavardhana** [comment]
> Can we reopen this, I'm still seeing the same panic in `RELEASE.2020-04-28T23-56-56Z`

@erhlee-bird can you provide more details, I can't seem to reproduce it from any version. Please provide a new backtrace of the crash.

**Comment by erhlee-bird** [comment]
```
Apr 29 12:51:50 ch09 systemd[1]: Started MinIO.
Apr 29 12:51:52 ch09 minio[3455000]: panic: runtime error: index out of range [1] with length 0
Apr 29 12:51:52 ch09 minio[3455000]: goroutine 1 [running]:
Apr 29 12:51:52 ch09 minio[3455000]: github.com/minio/minio/cmd.newXLSets(0x1fe0940, 0xc0002e1c80, 0xc000870000, 0x168, 0x180, 0xc00714a000, 0x168, 0x168, 0xc007230c80, 0xc00714a000, ...)
Apr 29 12:51:52 ch09 minio[3455000]:         github.com/minio/minio@/cmd/xl-sets.go:356 +0x1190
Apr 29 12:51:52 ch09 minio[3455000]: github.com/minio/minio/cmd.newXLZones(0x1fe0940, 0xc0002e1c80, 0xc0006fd710, 0x1, 0x1, 0xc000793590, 0x8, 0x180, 0x14df381)
Apr 29 12:51:52 ch09 minio[3455000]:         github.com/minio/minio@/cmd/xl-zones.go:85 +0x320
Apr 29 12:51:52 ch09 minio[3455000]: github.com/minio/minio/cmd.newObjectLayer(0x1fe0940, 0xc0002e1c80, 0xc0006fd710, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
Apr 29 12:51:52 ch09 minio[3455000]:         github.com/minio/minio@/cmd/server-main.go:499 +0xfc
Apr 29 12:51:52 ch09 minio[3455000]: github.com/minio/minio/cmd.serverMain(0xc000102b60)
Apr 29 12:51:52 ch09 minio[3455000]:         github.com/minio/minio@/cmd/server-main.go:425 +0x8ef
Apr 29 12:51:52 ch09 minio[3455000]: github.com/minio/cli.HandleAction(0x18b4960, 0x1cafbb0, 0xc000102b60, 0xc000260a00, 0x0)
Apr 29 12:51:52 ch09 minio[3455000]:         github.com/minio/cli@v1.22.0/app.go:500 +0x7c
Apr 29 12:51:52 ch09 minio[3455000]: github.com/minio/cli.Command.Run(0x1c1e992, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1c46cfb, 0x1b, 0x0, ...)
Apr 29 12:51:52 ch09 minio[3455000]:         github.com/minio/cli@v1.22.0/command.go:225 +0x991
Apr 29 12:51:52 ch09 minio[3455000]: github.com/minio/cli.(*App).Run(0xc0001021a0, 0xc00003a050, 0x5, 0x5, 0x0, 0x0)
Apr 29 12:51:52 ch09 minio[3455000]:         github.com/minio/cli@v1.22.0/app.go:261 +0x6ab
Apr 29 12:51:52 ch09 minio[3455000]: github.com/minio/minio/cmd.Main(0xc00003a050, 0x5, 0x5)
Apr 29 12:51:52 ch09 minio[3455000]:         github.com/minio/minio@/cmd/main.go:169 +0x89
Apr 29 12:51:52 ch09 minio[3455000]: main.main()
Apr 29 12:51:52 ch09 minio[3455000]:         github.com/minio/minio@/main.go:37 +0x45
Apr 29 12:51:52 ch09 systemd[1]: minio.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 29 12:51:52 ch09 systemd[1]: minio.service: Failed with result 'exit-code'.
Apr 29 12:51:52 ch09 systemd[1]: minio.service: Service hold-off time over, scheduling restart.
Apr 29 12:51:52 ch09 systemd[1]: minio.service: Scheduled restart job, restart counter is at 19.
Apr 29 12:51:52 ch09 systemd[1]: Stopped MinIO.
```

**Comment by erhlee-bird** [comment]
I've been rolling back to the following versions

```
minio.RELEASE.2020-03-14T02-21-58Z

minio.RELEASE.2020-03-19T21-49-00Z
```

These 2 versions are where I see some behavior discrepancies.

If I run `mc admin info`

```
●  minio-2:9000
   Uptime: a long while 
   Version: 2020-03-14T02:21:58Z
   Network: 2/2 OK 
   Drives: 180/180 OK 

●  minio-1:9000
   Uptime: a long while 
   Version: 2020-03-14T02:21:58Z
   Network: 2/2 OK 
   Drives: 180/180 OK 

393 TiB Used, 21 Buckets, 309,904,241 Objects
360 drives online, 0 drives offline
```

```
●  minio-2:9000
   Uptime: 7 seconds 
   Version: 2020-03-19T21:49:00Z
   Network: 2/2 OK 
   Drives: 180/180 OK 

●  minio-1:9000
   Uptime: 10 seconds 
   Version: 2020-03-19T21:49:00Z
   Network: 2/2 OK 
   Drives: 180/180 OK 

21 TiB Used, 21 Buckets, 5,988,957 Objects
360 drives online, 0 drives offline
```

Is it possible that I need to let the data usage crawlers finish as it seems that data is being stored differently?

**Comment by harshavardhana** [comment]
> ```
> Apr 29 12:51:50 ch09 systemd[1]: Started MinIO.
> Apr 29 12:51:52 ch09 minio[3455000]: panic: runtime error: index out of range [1] with length 0
> Apr 29 12:51:52 ch09 minio[3455000]: goroutine 1 [running]:
> Apr 29 12:51:52 ch09 minio[3455000]: github.com/minio/minio/cmd.newXLSets(0x1fe0940, 0xc0002e1c80, 0xc000870000, 0x168, 0x180, 0xc00714a000, 0x168, 0x168, 0xc007230c80, 0xc00714a000, ...)
> Apr 29 12:51:52 ch09 minio[3455000]:         github.com/minio/minio@/cmd/xl-sets.go:356 +0x1190
> Apr 29 12:51:52 ch09 minio[3455000]: github.com/minio/minio/cmd.newXLZones(0x1fe0940, 0xc0002e1c80, 0xc0006fd710, 0x1, 0x1, 0xc000793590, 0x8, 0x180, 0x14df381)
> Apr 29 12:51:52 ch09 minio[3455000]:         github.com/minio/minio@/cmd/xl-zones.go:85 +0x320
> Apr 29 12:51:52 ch09 minio[3455000]: github.com/minio/minio/cmd.newObjectLayer(0x1fe0940, 0xc0002e1c80, 0xc0006fd710, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
> Apr 29 12:51:52 ch09 minio[3455000]:         github.com/minio/minio@/cmd/server-main.go:499 +0xfc
> Apr 29 12:51:52 ch09 minio[3455000]: github.com/minio/minio/cmd.serverMain(0xc000102b60)
> Apr 29 12:51:52 ch09 minio[3455000]:         github.com/minio/minio@/cmd/server-main.go:425 +0x8ef
> Apr 29 12:51:52 ch09 minio[3455000]: github.com/minio/cli.HandleAction(0x18b4960, 0x1cafbb0, 0xc000102b60, 0xc000260a00, 0x0)
> Apr 29 12:51:52 ch09 minio[3455000]:         github.com/minio/cli@v1.22.0/app.go:500 +0x7c
> Apr 29 12:51:52 ch09 minio[3455000]: github.com/minio/cli.Command.Run(0x1c1e992, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1c46cfb, 0x1b, 0x0, ...)
> Apr 29 12:51:52 ch09 minio[3455000]:         github.com/minio/cli@v1.22.0/command.go:225 +0x991
> Apr 29 12:51:52 ch09 minio[3455000]: github.com/minio/cli.(*App).Run(0xc0001021a0, 0xc00003a050, 0x5, 0x5, 0x0, 0x0)
> Apr 29 12:51:52 ch09 minio[3455000]:         github.com/minio/cli@v1.22.0/app.go:261 +0x6ab
> Apr 29 12:51:52 ch09 minio[3455000]: github.com/minio/minio/cmd.Main(0xc00003a050, 0x5, 0x5)
> Apr 29 12:51:52 ch09 minio[3455000]:         github.com/minio/minio@/cmd/main.go:169 +0x89
> Apr 29 12:51:52 ch09 minio[3455000]: main.main()
> Apr 29 12:51:52 ch09 minio[3455000]:         github.com/minio/minio@/main.go:37 +0x45
> Apr 29 12:51:52 ch09 systemd[1]: minio.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
> Apr 29 12:51:52 ch09 systemd[1]: minio.service: Failed with result 'exit-code'.
> Apr 29 12:51:52 ch09 systemd[1]: minio.service: Service hold-off time over, scheduling restart.
> Apr 29 12:51:52 ch09 systemd[1]: minio.service: Scheduled restart job, restart counter is at 19.
> Apr 29 12:51:52 ch09 systemd[1]: Stopped MinIO.
> ```

Okay, so the only way this can happen is you have/had a drive that has more entries in `format.json` - than your erasure set count? 

[minio.gz](https://github.com/minio/minio/files/4553328/minio.gz)

Please paste the error in the crash that you see after using this binary. 

> Is it possible that I need to let the data usage crawlers finish as it seems that data is being stored differently?

you need to let it finish @erhlee-bird

**Comment by erhlee-bird** [comment]
```
Apr 29 13:49:15 ch09 systemd[1]: Started MinIO.
Apr 29 13:49:17 ch09 minio[3471684]: findDiskIndexByDiskID 15 1 30 12 /mnt/disk1
Apr 29 13:49:17 ch09 minio[3471684]: panic: runtime error: index out of range [1] with length 0
Apr 29 13:49:17 ch09 minio[3471684]: goroutine 1 [running]:
Apr 29 13:49:17 ch09 minio[3471684]: github.com/minio/minio/cmd.newXLSets(0x1fe09c0, 0xc0000f1b80, 0xc000866000, 0x168, 0x180, 0xc00721e000, 0x168, 0x168, 0xc007415e00, 0xc00721e000, ...)
Apr 29 13:49:17 ch09 minio[3471684]:         /home/harsha/mygo/src/github.com/minio/minio/cmd/xl-sets.go:357 +0x132a
Apr 29 13:49:17 ch09 minio[3471684]: github.com/minio/minio/cmd.newXLZones(0x1fe09c0, 0xc0000f1b80, 0xc0006f0f60, 0x1, 0x1, 0xc0007d3590, 0x8, 0x180, 0x14df3c1)
Apr 29 13:49:17 ch09 minio[3471684]:         /home/harsha/mygo/src/github.com/minio/minio/cmd/xl-zones.go:85 +0x320
Apr 29 13:49:17 ch09 minio[3471684]: github.com/minio/minio/cmd.newObjectLayer(0x1fe09c0, 0xc0000f1b80, 0xc0006f0f60, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
Apr 29 13:49:17 ch09 minio[3471684]:         /home/harsha/mygo/src/github.com/minio/minio/cmd/server-main.go:499 +0xfc
Apr 29 13:49:17 ch09 minio[3471684]: github.com/minio/minio/cmd.serverMain(0xc000102b60)
Apr 29 13:49:17 ch09 minio[3471684]:         /home/harsha/mygo/src/github.com/minio/minio/cmd/server-main.go:425 +0x8ef
Apr 29 13:49:17 ch09 minio[3471684]: github.com/minio/cli.HandleAction(0x18b4960, 0x1cafbd8, 0xc000102b60, 0xc0000d2d00, 0x0)
Apr 29 13:49:17 ch09 minio[3471684]:         /home/harsha/mygo/pkg/mod/github.com/minio/cli@v1.22.0/app.go:500 +0x7c
Apr 29 13:49:17 ch09 minio[3471684]: github.com/minio/cli.Command.Run(0x1c1e992, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1c46d21, 0x1b, 0x0, ...)
Apr 29 13:49:17 ch09 minio[3471684]:         /home/harsha/mygo/pkg/mod/github.com/minio/cli@v1.22.0/command.go:225 +0x991
Apr 29 13:49:17 ch09 minio[3471684]: github.com/minio/cli.(*App).Run(0xc0001021a0, 0xc00003a050, 0x5, 0x5, 0x0, 0x0)
Apr 29 13:49:17 ch09 minio[3471684]:         /home/harsha/mygo/pkg/mod/github.com/minio/cli@v1.22.0/app.go:261 +0x6ab
Apr 29 13:49:17 ch09 minio[3471684]: github.com/minio/minio/cmd.Main(0xc00003a050, 0x5, 0x5)
Apr 29 13:49:17 ch09 minio[3471684]:         /home/harsha/mygo/src/github.com/minio/minio/cmd/main.go:169 +0x89
Apr 29 13:49:17 ch09 minio[3471684]: main.main()
Apr 29 13:49:17 ch09 minio[3471684]:         /home/harsha/mygo/src/github.com/minio/minio/main.go:37 +0x45
Apr 29 13:49:17 ch09 systemd[1]: minio.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

Is there a good way to track the status of the crawler? It's going to take a long time.

**Comment by erhlee-bird** [comment]
```
cat /mnt/disk*/.minio.sys/format.json | jq '.xl.sets[] | length' | sort | uniq -c
   5400 12
```

```
cat /mnt/disk*/.minio.sys/format.json | jq '.xl.sets[] | length' | sort | uniq -c
   5400 12
```

The config files all seem to indicate 12 disk sets.

**Comment by harshavardhana** [comment]
> Is there a good way to track the status of the crawler? It's going to take a long time.

Yes it is going to in a slow manner @erhlee-bird

**Comment by erhlee-bird** [comment]
Is there a way to track the status of the crawler?

**Comment by harshavardhana** [comment]
> Apr 29 13:49:17 ch09 minio[3471684]: findDiskIndexByDiskID 15 1 30 12 /mnt/disk1

See this @erhlee-bird your /mnt/disk1/ indicates that it has 15 for some reason - it's not possible unless you had replaced drives and MinIO formatted them in a previous upgrade.


> Is there a way to track the status of the crawler?

No @erhlee-bird

**Comment by erhlee-bird** [comment]
These are all the original disks that we've used from the original setup.

Is there a file aside from the `.minio.sys/format.json` that would contain such information? Like what I posted above, it looks like all the disks are reporting 12.

**Comment by harshavardhana** [comment]
I think I found the problem - its because your order of disks how they were formatted has been different from the past since MinIO automatically re-orders them in memory in their right position.

In newer releases, we optimized this for large disk setups to re-use our storage drives but the loop which is trying to load them into the right position is assuming few things which weren't true in the past.

[minio.gz](https://github.com/minio/minio/files/4553550/minio.gz)

**Comment by erhlee-bird** [comment]
That one came up successfully!

**Comment by harshavardhana** [comment]
> That one came up successfully!

Fix will be available in next release.
