### ISSUE TITLE
upload a zip file by presigned url

### ISSUE THREAD

**Issue by yuyuanshifu** [minio/minio#9782]
## Steps to Reproduce (for bugs)

1.Get a presigned put url
2.upload a zip file by the url
3.download the zip file
4.unzip the file
5. the file size is changed, and cannot unzip it in windows env, I can unzip it in linux env,but an error would occur: exit status 1

## Your Environment

* Version used (`minio version`):RELEASE.2019-10-12T01-39-57Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by nitisht** [comment]
> Version used (minio version):RELEASE.2019-10-12T01-39-57Z

This is pretty old release. Please try with the latest release, the issue should be fixed.

**Comment by yuyuanshifu** [comment]
> > Version used (minio version):RELEASE.2019-10-12T01-39-57Z
> 
> This is pretty old release. Please try with the latest release, the issue should be fixed.

I tried the new version:RELEASE.2020-06-03T22-13-49Z
But I still have this problem

**Comment by kannappanr** [comment]
@yuyuanshifu I tried with the latest release and used `minio-js` to generate a pre-signed PUT object. I verified with both Windows and Linux that the object uploaded matches the original object size. I was also able to download it, extract it properly.

**Comment by yuyuanshifu** [comment]
> @yuyuanshifu I tried with the latest release and used `minio-js` to generate a pre-signed PUT object. I verified with both Windows and Linux that the object uploaded matches the original object size. I was also able to download it, extract it properly.

Thx. Finally I found the problem: I uploaded the file with content-type:form. I have solved the problem.

**Comment by yuyuanshifu** [comment]
[https://github.com/rowanwins/vue-dropzone/issues/411#issuecomment-459255756](url)

**Comment by yuyuanshifu** [comment]
https://github.com/rowanwins/vue-dropzone/issues/411#issuecomment-459255756
